-- BASELINE -- the schema as it existed immediately BEFORE the first migration.
--
-- WHY THIS EXISTS
-- This project's production database was created with `prisma db push`, so the
-- migrations folder started life mid-history: the earliest migration
-- (20260705000000_add_episode_tts_provider) ALTERs "Episode", a table no
-- migration ever created. Against an empty database `prisma migrate deploy`
-- therefore failed with `relation "Episode" does not exist` -- meaning the
-- repository could not rebuild its own schema. That is fine until the day it
-- isn't: disaster recovery, a new staging environment, and any audit of "does
-- our history actually describe our database?" all need a fresh database to be
-- reconstructible from migrations alone. The E2E harness hid this by using
-- `db push`.
--
-- HOW IT WAS RECONSTRUCTED -- from git history, NOT from the current schema.
--   source commit: cc8fd4913ac61cbe4b4322075a6618207ee31490
--                  (the parent of 4f406e048c10f4a3c412bc93550f4f6c69e8a1a5,
--                   which introduced the first migration)
--   generated by:  prisma migrate diff --from-empty \
--                    --to-schema-datamodel <that commit's prisma/schema.prisma> \
--                    --script
--
-- Generating this from the CURRENT schema would have been the tempting mistake:
-- the 18 later migrations would then try to add columns, enums and tables that
-- already existed, and a fresh deploy would fail on duplicates instead of
-- missing relations. So this contains ONLY what existed on 2026-07-05:
-- 20 tables, no enums. Notably absent, because later migrations add them:
--   * Episode.ttsProvider            (20260705000000 -- the next migration)
--   * the TopicEditorialStatus enum  (20260714120000; status is still TEXT here)
--   * EpisodeTopic.snapshot/selectedAt (20260714120000)
--   * Podcast, StudioDraft, AdminDraft, TopicSource, SocialClip, PlayEvent,
--     AudioAsset, SoundCueUsage, and every auth/ownership column.
--
-- ADOPTING AN EXISTING DATABASE
-- An environment created by `db push` already HAS these tables and must never
-- run this migration. Use `npm run audit:migration-adoption` first -- it is
-- read-only and tells you which checkpoint the database matches and whether
-- `migrate resolve --applied` is safe. Never mark a migration applied merely to
-- silence Prisma.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" TEXT NOT NULL DEFAULT 'USER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiHost" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "worldview" TEXT NOT NULL,
    "speakingStyle" TEXT NOT NULL,
    "catchphrases" JSONB NOT NULL,
    "likes" JSONB NOT NULL,
    "dislikes" JSONB NOT NULL,
    "argumentPatterns" JSONB NOT NULL,
    "bannedPhrases" JSONB NOT NULL,
    "ttsProvider" TEXT NOT NULL,
    "ttsVoiceId" TEXT NOT NULL,
    "intensityLevel" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AiHost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SportsDataSource" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "baseUrl" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastIngestedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SportsDataSource_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "League" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sport" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "League_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Team" (
    "id" TEXT NOT NULL,
    "leagueId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "abbreviation" TEXT NOT NULL,
    "slug" TEXT NOT NULL,

    CONSTRAINT "Team_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Player" (
    "id" TEXT NOT NULL,
    "leagueId" TEXT NOT NULL,
    "teamId" TEXT,
    "name" TEXT NOT NULL,
    "position" TEXT,
    "status" TEXT,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Game" (
    "id" TEXT NOT NULL,
    "leagueId" TEXT NOT NULL,
    "homeTeamId" TEXT NOT NULL,
    "awayTeamId" TEXT NOT NULL,
    "scheduledAt" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL,
    "homeScore" INTEGER,
    "awayScore" INTEGER,
    "sourceId" TEXT,
    "raw" JSONB NOT NULL,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TeamStat" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "leagueId" TEXT NOT NULL,
    "season" TEXT NOT NULL,
    "statType" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "sourceId" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TeamStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlayerStat" (
    "id" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "teamId" TEXT,
    "leagueId" TEXT NOT NULL,
    "season" TEXT NOT NULL,
    "statType" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "sourceId" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlayerStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Injury" (
    "id" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "teamId" TEXT,
    "status" TEXT,
    "description" TEXT,
    "reportedAt" TIMESTAMP(3) NOT NULL,
    "sourceId" TEXT,
    "sourceUrl" TEXT,

    CONSTRAINT "Injury_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OddsSnapshot" (
    "id" TEXT NOT NULL,
    "gameId" TEXT NOT NULL,
    "sportsbook" TEXT NOT NULL,
    "market" TEXT NOT NULL,
    "line" DOUBLE PRECISION,
    "price" DOUBLE PRECISION,
    "impliedProbability" DOUBLE PRECISION,
    "capturedAt" TIMESTAMP(3) NOT NULL,
    "sourceId" TEXT,
    "raw" JSONB NOT NULL,

    CONSTRAINT "OddsSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NewsItem" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "publishedAt" TIMESTAMP(3) NOT NULL,
    "summary" TEXT,
    "entities" JSONB NOT NULL,
    "raw" JSONB NOT NULL,

    CONSTRAINT "NewsItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TopicCandidate" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "sport" TEXT NOT NULL,
    "leagueId" TEXT,
    "summary" TEXT,
    "controversyScore" DOUBLE PRECISION NOT NULL,
    "starPowerScore" DOUBLE PRECISION NOT NULL,
    "bettingRelevanceScore" DOUBLE PRECISION NOT NULL,
    "recencyScore" DOUBLE PRECISION NOT NULL,
    "debateScore" DOUBLE PRECISION NOT NULL,
    "evidenceIds" JSONB NOT NULL,
    "status" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TopicCandidate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResearchBrief" (
    "id" TEXT NOT NULL,
    "topicId" TEXT NOT NULL,
    "facts" JSONB NOT NULL,
    "stats" JSONB NOT NULL,
    "injuryContext" TEXT,
    "oddsContext" TEXT,
    "argumentForHostA" TEXT NOT NULL,
    "argumentForHostB" TEXT NOT NULL,
    "counterArguments" JSONB NOT NULL,
    "unsafeClaims" JSONB NOT NULL,
    "sourceIds" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "classification" TEXT,
    "mainAngle" TEXT,
    "whyMattersNow" TEXT,
    "keyFactsContext" JSONB,
    "onAirTalkingPoints" JSONB,
    "contrarianAngle" TEXT,
    "strongestDebateQuestion" TEXT,
    "suggestedHostTake" TEXT,
    "sourceNotesUsed" TEXT,

    CONSTRAINT "ResearchBrief_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Episode" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "description" TEXT,
    "longShowNotes" TEXT,
    "durationSeconds" INTEGER,
    "audioUrl" TEXT,
    "transcriptUrl" TEXT,
    "rssGuid" TEXT,
    "publishedAt" TIMESTAMP(3),
    "episodeNumber" INTEGER,
    "seasonNumber" INTEGER,
    "explicit" BOOLEAN NOT NULL DEFAULT false,
    "rssSummary" TEXT,
    "rssSubtitle" TEXT,
    "rssImageUrl" TEXT,
    "audioFileSizeBytes" INTEGER,
    "audioMimeType" TEXT NOT NULL DEFAULT 'audio/mpeg',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Episode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EpisodeTopic" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT NOT NULL,
    "topicId" TEXT NOT NULL,
    "orderIndex" INTEGER NOT NULL,

    CONSTRAINT "EpisodeTopic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Script" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "content" JSONB NOT NULL,
    "plainText" TEXT,
    "status" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Script_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FactCheckResult" (
    "id" TEXT NOT NULL,
    "scriptId" TEXT NOT NULL,
    "passed" BOOLEAN NOT NULL,
    "warnings" JSONB NOT NULL,
    "errors" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "episodeId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'needs_review',
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "provider" TEXT NOT NULL DEFAULT 'deterministic',
    "summary" JSONB,
    "issues" JSONB,
    "evidenceCoverage" JSONB,
    "rawResult" JSONB,

    CONSTRAINT "FactCheckResult_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AudioSegment" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT NOT NULL,
    "scriptId" TEXT NOT NULL,
    "hostId" TEXT,
    "lineIndex" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "audioUrl" TEXT,
    "durationMs" INTEGER,
    "status" TEXT NOT NULL,
    "provider" TEXT,
    "providerMetadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AudioSegment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobLog" (
    "id" TEXT NOT NULL,
    "jobType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "input" JSONB NOT NULL,
    "output" JSONB NOT NULL,
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "JobLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "AiHost_slug_key" ON "AiHost"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "SportsDataSource_name_key" ON "SportsDataSource"("name");

-- CreateIndex
CREATE UNIQUE INDEX "League_slug_key" ON "League"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Team_slug_key" ON "Team"("slug");

-- CreateIndex
CREATE INDEX "Team_leagueId_idx" ON "Team"("leagueId");

-- CreateIndex
CREATE INDEX "Player_leagueId_idx" ON "Player"("leagueId");

-- CreateIndex
CREATE INDEX "Player_teamId_idx" ON "Player"("teamId");

-- CreateIndex
CREATE INDEX "Game_leagueId_idx" ON "Game"("leagueId");

-- CreateIndex
CREATE INDEX "Game_homeTeamId_idx" ON "Game"("homeTeamId");

-- CreateIndex
CREATE INDEX "Game_awayTeamId_idx" ON "Game"("awayTeamId");

-- CreateIndex
CREATE INDEX "Game_scheduledAt_idx" ON "Game"("scheduledAt");

-- CreateIndex
CREATE INDEX "TeamStat_teamId_idx" ON "TeamStat"("teamId");

-- CreateIndex
CREATE INDEX "TeamStat_leagueId_idx" ON "TeamStat"("leagueId");

-- CreateIndex
CREATE INDEX "TeamStat_season_statType_idx" ON "TeamStat"("season", "statType");

-- CreateIndex
CREATE INDEX "PlayerStat_playerId_idx" ON "PlayerStat"("playerId");

-- CreateIndex
CREATE INDEX "PlayerStat_teamId_idx" ON "PlayerStat"("teamId");

-- CreateIndex
CREATE INDEX "PlayerStat_leagueId_idx" ON "PlayerStat"("leagueId");

-- CreateIndex
CREATE INDEX "PlayerStat_season_statType_idx" ON "PlayerStat"("season", "statType");

-- CreateIndex
CREATE INDEX "Injury_playerId_idx" ON "Injury"("playerId");

-- CreateIndex
CREATE INDEX "Injury_teamId_idx" ON "Injury"("teamId");

-- CreateIndex
CREATE INDEX "OddsSnapshot_gameId_idx" ON "OddsSnapshot"("gameId");

-- CreateIndex
CREATE INDEX "OddsSnapshot_sportsbook_idx" ON "OddsSnapshot"("sportsbook");

-- CreateIndex
CREATE INDEX "OddsSnapshot_capturedAt_idx" ON "OddsSnapshot"("capturedAt");

-- CreateIndex
CREATE INDEX "NewsItem_publishedAt_idx" ON "NewsItem"("publishedAt");

-- CreateIndex
CREATE INDEX "TopicCandidate_leagueId_idx" ON "TopicCandidate"("leagueId");

-- CreateIndex
CREATE INDEX "TopicCandidate_status_idx" ON "TopicCandidate"("status");

-- CreateIndex
CREATE INDEX "TopicCandidate_createdAt_idx" ON "TopicCandidate"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "ResearchBrief_topicId_key" ON "ResearchBrief"("topicId");

-- CreateIndex
CREATE UNIQUE INDEX "Episode_slug_key" ON "Episode"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Episode_rssGuid_key" ON "Episode"("rssGuid");

-- CreateIndex
CREATE INDEX "Episode_status_idx" ON "Episode"("status");

-- CreateIndex
CREATE INDEX "Episode_publishedAt_idx" ON "Episode"("publishedAt");

-- CreateIndex
CREATE INDEX "EpisodeTopic_episodeId_idx" ON "EpisodeTopic"("episodeId");

-- CreateIndex
CREATE INDEX "EpisodeTopic_topicId_idx" ON "EpisodeTopic"("topicId");

-- CreateIndex
CREATE UNIQUE INDEX "EpisodeTopic_episodeId_topicId_key" ON "EpisodeTopic"("episodeId", "topicId");

-- CreateIndex
CREATE INDEX "Script_episodeId_idx" ON "Script"("episodeId");

-- CreateIndex
CREATE INDEX "Script_status_idx" ON "Script"("status");

-- CreateIndex
CREATE INDEX "FactCheckResult_scriptId_idx" ON "FactCheckResult"("scriptId");

-- CreateIndex
CREATE INDEX "AudioSegment_episodeId_idx" ON "AudioSegment"("episodeId");

-- CreateIndex
CREATE INDEX "AudioSegment_scriptId_idx" ON "AudioSegment"("scriptId");

-- CreateIndex
CREATE INDEX "AudioSegment_lineIndex_idx" ON "AudioSegment"("lineIndex");

-- CreateIndex
CREATE INDEX "JobLog_jobType_idx" ON "JobLog"("jobType");

-- CreateIndex
CREATE INDEX "JobLog_status_idx" ON "JobLog"("status");

-- CreateIndex
CREATE INDEX "JobLog_createdAt_idx" ON "JobLog"("createdAt");

-- AddForeignKey
ALTER TABLE "Team" ADD CONSTRAINT "Team_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_homeTeamId_fkey" FOREIGN KEY ("homeTeamId") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_awayTeamId_fkey" FOREIGN KEY ("awayTeamId") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamStat" ADD CONSTRAINT "TeamStat_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamStat" ADD CONSTRAINT "TeamStat_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Injury" ADD CONSTRAINT "Injury_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Injury" ADD CONSTRAINT "Injury_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OddsSnapshot" ADD CONSTRAINT "OddsSnapshot_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TopicCandidate" ADD CONSTRAINT "TopicCandidate_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResearchBrief" ADD CONSTRAINT "ResearchBrief_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "TopicCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EpisodeTopic" ADD CONSTRAINT "EpisodeTopic_episodeId_fkey" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EpisodeTopic" ADD CONSTRAINT "EpisodeTopic_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "TopicCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Script" ADD CONSTRAINT "Script_episodeId_fkey" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FactCheckResult" ADD CONSTRAINT "FactCheckResult_scriptId_fkey" FOREIGN KEY ("scriptId") REFERENCES "Script"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AudioSegment" ADD CONSTRAINT "AudioSegment_episodeId_fkey" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AudioSegment" ADD CONSTRAINT "AudioSegment_scriptId_fkey" FOREIGN KEY ("scriptId") REFERENCES "Script"("id") ON DELETE CASCADE ON UPDATE CASCADE;

