"use client";

// "Add Custom Topic" / "Import from URL" — the operator's way to put an
// editorial idea into the pipeline.
//
// Everything fetched is rendered as TEXT. There is no dangerouslySetInnerHTML
// here and there must never be: the values below come from pages we do not
// control, and React escaping is what makes a hostile <script> in a page title
// a harmless string on screen.
//
// The panel is deliberately honest about what it just made: a pending topic
// with no evidence and no research is shown as exactly that, with the real next
// actions, rather than a green tick implying it is ready to air.

import React, { useId, useRef, useState } from "react";
import { createCustomTopicAction, fetchTopicSourcesAction } from "./ingestionActions";
// From the dependency-free limits module, NOT from the ingestion service: this
// is a client component, and the service transitively imports the fetcher's
// node:https / node:dns / node:zlib, which cannot exist in a browser bundle.
import { FETCH_LIMITS } from "@/lib/net/fetchLimits";

const MAX_URLS_PER_REQUEST = FETCH_LIMITS.maxUrlsPerRequest;

interface SourceResult {
  url: string;
  status: string;
  message: string;
  canonicalUrl?: string;
  title?: string | null;
  publisher?: string | null;
  retryable: boolean;
}

interface CreatedTopic {
  topicId: string;
  editorialStatus: string;
  sources: SourceResult[];
  importedSourceCount: number;
  failedSourceCount: number;
  researchReadiness: string;
  deduplicated: boolean;
  duplicateWarning?: { topicId: string; title: string; reason: string };
  nextActions: string[];
}

interface SourcePreview {
  id: string;
  canonicalUrl: string;
  title: string | null;
  publisher: string | null;
  author: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  fetchStatus: string;
  retrievedAt: string | null;
}

/** Short labels for the per-URL outcome. The detail lives in `message`. */
const STATUS_LABEL: Record<string, string> = {
  imported: "Imported",
  duplicate: "Duplicate",
  invalid_url: "Invalid URL",
  unsupported_protocol: "Unsupported link",
  embedded_credentials: "Credentials in URL",
  url_too_long: "URL too long",
  blocked_destination: "Blocked",
  redirect_blocked: "Blocked redirect",
  too_many_redirects: "Too many redirects",
  dns_resolution_failed: "Not found",
  timeout: "Timed out",
  response_too_large: "Too large",
  unsupported_content_type: "Not an article",
  tls_error: "Certificate problem",
  fetch_failed: "Fetch failed",
};

export default function CustomTopicPanel({ onCreated }: { onCreated?: (topicId: string) => void }) {
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [angle, setAngle] = useState("");
  const [notes, setNotes] = useState("");
  const [sport, setSport] = useState("");
  const [leagueId, setLeagueId] = useState("");
  const [teamsOrPlayers, setTeamsOrPlayers] = useState("");
  const [urlText, setUrlText] = useState("");

  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<CreatedTopic | null>(null);
  const [preview, setPreview] = useState<SourcePreview[] | null>(null);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [live, setLive] = useState("");

  // One key per FORM instance: a double-click (or a retry after a network
  // wobble) resolves to the SAME topic instead of a second one. Minted lazily
  // in the submit handler rather than during render — render must stay pure,
  // and a key regenerated by an incidental re-render would defeat the point.
  const idempotencyKey = useRef<string | null>(null);
  const formId = useId();

  const urls = urlText.split(/[\s,]+/).map((u) => u.trim()).filter(Boolean);
  const tooManyUrls = urls.length > MAX_URLS_PER_REQUEST;
  const canSubmit = title.trim().length > 0 && !tooManyUrls && !busy;

  const reset = () => {
    setTitle(""); setAngle(""); setNotes(""); setSport(""); setLeagueId(""); setTeamsOrPlayers(""); setUrlText("");
    setCreated(null); setPreview(null); setPreviewOpen(false); setError(null);
    // A genuinely new submission deserves a new key.
    idempotencyKey.current = null;
  };

  const submit = async () => {
    if (!canSubmit) return;
    // Minted once per submission attempt and REUSED on retry, so a repeat of
    // the same submit resolves to the same topic.
    if (!idempotencyKey.current) idempotencyKey.current = `custom-${crypto.randomUUID()}`;
    setBusy(true);
    setError(null);
    setCreated(null);
    try {
      const res = await createCustomTopicAction({
        title: title.trim(),
        angle: angle.trim() || null,
        notes: notes.trim() || null,
        sport: sport.trim() || null,
        leagueId: leagueId.trim() || null,
        teamsOrPlayers: teamsOrPlayers.trim() || null,
        sourceUrls: urls,
        idempotencyKey: idempotencyKey.current,
      });
      if (!res.ok) {
        setError(res.error);
        setLive(`Couldn't create the topic: ${res.error}`);
        return;
      }
      setCreated(res as CreatedTopic);
      setLive(
        `Topic created and pending approval. ${res.importedSourceCount} source${res.importedSourceCount === 1 ? "" : "s"} imported, ${res.failedSourceCount} failed.`
      );
      onCreated?.(res.topicId);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  };

  const loadPreview = async () => {
    if (!created) return;
    const res = await fetchTopicSourcesAction(created.topicId);
    if (res.ok) {
      setPreview(res.sources as SourcePreview[]);
      setPreviewOpen(true);
    } else {
      setError(res.error);
    }
  };

  return (
    <div className="studioCard" style={{ padding: "0.85rem 1rem", marginBottom: "0.8rem" }} data-testid="custom-topic-panel">
      <div aria-live="polite" data-testid="ct-live-region" style={{ position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0 0 0 0)" }}>
        {live}
      </div>

      <button
        type="button"
        className={open ? "btnGhost" : "btnPrimary"}
        data-testid="add-custom-topic"
        aria-expanded={open}
        aria-controls={formId}
        onClick={() => setOpen((v) => !v)}
      >
        {open ? "Close" : "Add Custom Topic"}
      </button>

      {open && (
        <div id={formId} style={{ marginTop: "0.85rem" }}>
          <p className="stageHint" style={{ marginTop: 0 }} data-testid="custom-topic-note">
            Your notes are editorial input, not verified facts. The topic is created <strong>pending approval</strong> with
            no research and no evidence — it has to earn those before it can go in an episode.
          </p>

          <label className="fieldLabel" htmlFor={`${formId}-title`}>Topic title <span aria-hidden="true">*</span></label>
          <input id={`${formId}-title`} data-testid="ct-title" className="input" value={title} required
            aria-required="true" onChange={(e) => setTitle(e.target.value)} placeholder="What's the argument?" />

          <label className="fieldLabel" htmlFor={`${formId}-angle`} style={{ marginTop: "0.6rem" }}>Editorial angle (optional)</label>
          <input id={`${formId}-angle`} data-testid="ct-angle" className="input" value={angle}
            onChange={(e) => setAngle(e.target.value)} placeholder="The contrarian take you want explored" />

          <label className="fieldLabel" htmlFor={`${formId}-notes`} style={{ marginTop: "0.6rem" }}>Summary / editorial notes (optional)</label>
          <textarea id={`${formId}-notes`} data-testid="ct-notes" className="input" rows={2} value={notes}
            onChange={(e) => setNotes(e.target.value)} />

          <div className="rundownPrefsGrid" style={{ marginTop: "0.6rem" }}>
            <div>
              <label className="fieldLabel" htmlFor={`${formId}-sport`}>Sport (optional)</label>
              <input id={`${formId}-sport`} data-testid="ct-sport" className="input" value={sport} onChange={(e) => setSport(e.target.value)} />
            </div>
            <div>
              <label className="fieldLabel" htmlFor={`${formId}-league`}>League (optional)</label>
              <input id={`${formId}-league`} data-testid="ct-league" className="input" value={leagueId} onChange={(e) => setLeagueId(e.target.value)} />
            </div>
          </div>

          <label className="fieldLabel" htmlFor={`${formId}-entities`} style={{ marginTop: "0.6rem" }}>Teams or players (optional)</label>
          <input id={`${formId}-entities`} data-testid="ct-entities" className="input" value={teamsOrPlayers}
            onChange={(e) => setTeamsOrPlayers(e.target.value)} placeholder="e.g. Chiefs, Mahomes" />
          <p className="stageHint" style={{ margin: "0.2rem 0 0", fontSize: "0.75rem" }} data-testid="ct-entities-note">
            Free text. There is no structured team/player link for hand-written topics, so this is passed to research as context only.
          </p>

          <label className="fieldLabel" htmlFor={`${formId}-urls`} style={{ marginTop: "0.6rem" }}>
            Source URLs (optional) — up to {MAX_URLS_PER_REQUEST}
          </label>
          <textarea id={`${formId}-urls`} data-testid="ct-urls" className="input" rows={3} value={urlText}
            onChange={(e) => setUrlText(e.target.value)} placeholder={"https://example.com/article\nhttps://example.com/another"}
            aria-describedby={`${formId}-urls-note`} />
          <p id={`${formId}-urls-note`} className="stageHint" style={{ margin: "0.2rem 0 0", fontSize: "0.75rem" }}>
            One per line. Only http/https public pages are fetched; the text is imported as research material.
          </p>
          {tooManyUrls && (
            <p role="alert" data-testid="ct-too-many-urls" style={{ color: "var(--error-color, #b91c1c)", fontSize: "0.8rem" }}>
              That&apos;s {urls.length} URLs — import at most {MAX_URLS_PER_REQUEST} at a time.
            </p>
          )}

          {error && <p role="alert" data-testid="ct-error" style={{ color: "var(--error-color, #b91c1c)", fontSize: "0.82rem" }}>{error}</p>}

          <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.7rem", flexWrap: "wrap" }}>
            <button type="button" className="btnPrimary" data-testid="ct-submit" disabled={!canSubmit} aria-busy={busy} onClick={submit}>
              {busy ? "Creating…" : "Create pending topic"}
            </button>
            {created && (
              <button type="button" className="btnGhost" data-testid="ct-reset" onClick={reset}>
                Add another
              </button>
            )}
          </div>

          {/* -------- Result -------- */}
          {created && (
            <div className="studioCard" data-testid="ct-result" style={{ padding: "0.7rem 0.85rem", marginTop: "0.8rem" }}>
              <div className="epMeta" style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap", marginBottom: "0.3rem" }}>
                <span className="chip" data-testid="ct-status">Status: {created.editorialStatus}</span>
                <span className="chip" data-testid="ct-imported-count">{created.importedSourceCount} imported</span>
                {created.failedSourceCount > 0 && (
                  <span className="chip" data-testid="ct-failed-count" style={{ color: "var(--warning-color, #b45309)" }}>
                    {created.failedSourceCount} failed
                  </span>
                )}
                <span className="chip" data-testid="ct-research">Research: {created.researchReadiness.replace(/_/g, " ")}</span>
              </div>

              <p role="note" data-testid="ct-gates" style={{ fontSize: "0.82rem", margin: "0.3rem 0" }}>
                Created and <strong>pending approval</strong>. Approval is required before research can run, and it needs
                research and evidence before it can join an episode.
              </p>

              {created.deduplicated && (
                <p role="note" data-testid="ct-deduplicated" style={{ fontSize: "0.8rem", color: "var(--warning-color, #b45309)" }}>
                  This submission had already been processed — showing the topic it created.
                </p>
              )}
              {created.duplicateWarning && !created.deduplicated && (
                <p role="note" data-testid="ct-duplicate-warning" style={{ fontSize: "0.8rem", color: "var(--warning-color, #b45309)" }}>
                  ⚠ {created.duplicateWarning.reason} Existing topic: “{created.duplicateWarning.title}”. Yours was still created —
                  remove it if it was a mistake.
                </p>
              )}

              {created.sources.length > 0 && (
                <ul data-testid="ct-source-results" style={{ listStyle: "none", padding: 0, margin: "0.4rem 0 0", display: "flex", flexDirection: "column", gap: "0.3rem" }}>
                  {created.sources.map((s, i) => (
                    <li key={i} data-testid={`ct-source-${i}`} data-status={s.status}
                      style={{ fontSize: "0.8rem", display: "flex", gap: "0.4rem", flexWrap: "wrap", alignItems: "baseline" }}>
                      <span className="chip" style={{ color: s.status === "imported" ? undefined : "var(--warning-color, #b45309)" }}>
                        {STATUS_LABEL[s.status] ?? s.status}
                      </span>
                      {/* Untrusted values — rendered as text, never as markup. */}
                      <span style={{ overflowWrap: "anywhere" }}>{s.title || s.url}</span>
                      <span className="stageHint" style={{ fontSize: "0.75rem" }}>{s.message}</span>
                      {s.retryable && <span className="chip" data-testid={`ct-retryable-${i}`}>retryable</span>}
                    </li>
                  ))}
                </ul>
              )}

              <div style={{ display: "flex", gap: "0.6rem", marginTop: "0.5rem", flexWrap: "wrap" }}>
                {created.importedSourceCount > 0 && (
                  <button type="button" className="advLink" data-testid="ct-preview-sources" aria-expanded={previewOpen}
                    onClick={() => (previewOpen ? setPreviewOpen(false) : void loadPreview())}>
                    {previewOpen ? "Hide imported sources" : "Preview imported sources"}
                  </button>
                )}
                <span className="stageHint" style={{ fontSize: "0.75rem" }} data-testid="ct-next-actions">
                  Next: {created.nextActions.join(" → ").replace(/_/g, " ")}
                </span>
              </div>

              {previewOpen && preview && (
                <div className="briefBlock" data-testid="ct-source-preview" style={{ marginTop: "0.5rem", borderTop: "1px solid var(--border-color, #333)", paddingTop: "0.5rem" }}>
                  {preview.map((p) => (
                    <div key={p.id} data-testid={`ct-preview-${p.id}`} style={{ marginBottom: "0.6rem" }}>
                      {/* Every field below is sanitized plain text from an
                          untrusted page. React escapes it; nothing is injected. */}
                      <div className="epTitle" style={{ fontSize: "0.85rem" }}>{p.title || "(untitled)"}</div>
                      <div className="epMeta" style={{ display: "flex", gap: "0.35rem", flexWrap: "wrap" }}>
                        {p.publisher && <span className="chip">{p.publisher}</span>}
                        {p.author && <span className="chip">{p.author}</span>}
                        {p.publishedAt && <span className="chip">{p.publishedAt.slice(0, 10)}</span>}
                      </div>
                      <div style={{ fontSize: "0.78rem", color: "var(--text-secondary)", overflowWrap: "anywhere" }}>{p.canonicalUrl}</div>
                      {p.excerpt && (
                        <p style={{ fontSize: "0.78rem", marginTop: "0.25rem", display: "-webkit-box", WebkitLineClamp: 3, WebkitBoxOrient: "vertical", overflow: "hidden" }}>
                          {p.excerpt}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
