import React from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { SEED_TEAMS } from "@/lib/data/teamSeed";
import { friendlyStage } from "../../lib";
import { WEEKDAY_LABELS } from "../config";
import PodcastWizard, { WizardHost, WizardTeam } from "../new/PodcastWizard";
import GenerateNowButton from "../GenerateNowButton";
import { requireUserPage } from "@/lib/currentUser";

export const dynamic = "force-dynamic";

export default async function ManagePodcastPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireUserPage(`/app/podcasts/${id}`); // managing a podcast requires an account

  const podcast = await db.podcast
    .findUnique({
      where: { id },
      include: {
        episodes: { orderBy: { createdAt: "desc" }, take: 8, select: { id: true, title: true, status: true, createdAt: true, audioUrl: true } },
      },
    })
    .catch(() => null);
  if (!podcast) notFound();
  // Owner-only management (legacy null-owner podcasts stay open for continuity).
  if (podcast.ownerId && podcast.ownerId !== user.id) notFound();

  const [hostsRaw, teamsRaw] = await Promise.all([
    // Own + shared hosts only — never another account's roster.
    db.aiHost.findMany({ where: { isActive: true, isArchived: false, OR: [{ ownerId: user.id }, { ownerId: null }] }, orderBy: { name: "asc" }, select: { id: true, name: true, role: true } }).catch(() => [] as any[]),
    db.team.findMany({ where: { id: { startsWith: "seed:" } }, orderBy: [{ leagueId: "asc" }, { name: "asc" }], select: { id: true, leagueId: true, name: true } }).catch(() => [] as any[]),
  ]);
  const teams: WizardTeam[] = (teamsRaw.length > 0 ? teamsRaw : SEED_TEAMS).map((t: any) => ({ id: t.id, leagueId: t.leagueId, name: t.name }));
  const hosts: WizardHost[] = hostsRaw.map((h: any) => ({ id: h.id, name: h.name, role: h.role }));

  return (
    <>
      <div className="uTopbar">
        <h1 className="uPageTitle">{podcast.name}</h1>
        <div style={{ display: "flex", gap: "0.8rem", alignItems: "center" }}>
          <Link
            href={`/app/podcasts/${podcast.id}/sound`}
            data-testid="podcast-sound-branding-link"
            style={{
              textDecoration: "none",
              display: "inline-flex",
              alignItems: "center",
              gap: "0.4rem",
              background: "var(--u-surface)",
              color: "var(--u-ink)",
              border: "1px solid var(--u-hairline-2)",
              padding: "0.5rem 1rem",
              borderRadius: "999px",
              fontWeight: 600,
              fontSize: "0.85rem",
              boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
            }}
          >
            🎵 Sound &amp; Branding
          </Link>
          <GenerateNowButton podcastId={podcast.id} solid />
        </div>
      </div>
      <div className="uContent" style={{ maxWidth: 760 }}>
        <div className="uTakeMeta" style={{ marginBottom: "1.6rem", flexWrap: "wrap" }}>
          <span className="uHeat" style={{ background: "var(--u-brand-soft)", color: "var(--u-brand)" }}>
            {podcast.cadence === "recurring"
              ? `🔁 Every ${podcast.scheduleDays.map((d: string) => (WEEKDAY_LABELS[d] || d).slice(0, 3)).join(" · ")}`
              : "🎯 One-time"}
          </span>
          {podcast.lastAutoGeneratedDate && <span>Last auto-generated {podcast.lastAutoGeneratedDate}</span>}
          <Link href="/app/podcasts" style={{ color: "var(--u-brand)", fontWeight: 650 }}>← All podcasts</Link>
        </div>

        {podcast.episodes.length > 0 && (
          <>
            <h2 className="uSectionTitle" style={{ marginBottom: "0.8rem" }}>Episodes from this podcast</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.6rem", marginBottom: "2rem" }}>
              {podcast.episodes.map((ep) => (
                <Link key={ep.id} href={`/app/episodes/${ep.id}`} className="uTakeCard" style={{ textDecoration: "none", color: "inherit", justifyContent: "space-between", padding: "0.8rem 1rem" }}>
                  <div style={{ minWidth: 0 }}>
                    <div className="uTakeTitle" style={{ fontSize: "0.9rem" }}>{ep.title}</div>
                    <div className="uTakeMeta" style={{ marginTop: "0.3rem" }}>{friendlyStage(ep.status).label}</div>
                  </div>
                  <span className="uRecordBtn" style={{ flexShrink: 0 }}>{ep.audioUrl ? "▶ Listen" : "View"}</span>
                </Link>
              ))}
            </div>
          </>
        )}

        <h2 className="uSectionTitle" style={{ marginBottom: "0.8rem" }}>Settings</h2>
        <p style={{ fontSize: "0.84rem", color: "var(--u-ink-2)", marginBottom: "1.2rem" }}>
          Walk through the steps to change anything — edits apply to every future generation.
        </p>
        <PodcastWizard
          hosts={hosts}
          teams={teams}
          podcastId={podcast.id}
          initial={{
            name: podcast.name,
            cadence: podcast.cadence as "one_time" | "recurring",
            scheduleDays: podcast.scheduleDays,
            verticals: podcast.verticals,
            teams: podcast.teams,
            segmentCount: podcast.segmentCount,
            hostIds: podcast.hostIds,
          }}
        />
      </div>
    </>
  );
}
