-- Podcast grouping entity + nullable Episode.podcastId, and the seeded
-- team catalog for the creation wizard's verticals. Purely additive:
-- existing Episode rows get NULL podcastId; seeded League/Team rows use
-- ON CONFLICT DO NOTHING and "seed:" ids so ingestion-provider rows
-- ("sio:...") are never touched. IF NOT EXISTS keeps re-runs idempotent.

CREATE TABLE IF NOT EXISTS "Podcast" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cadence" TEXT NOT NULL,
    "scheduleDays" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "verticals" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "teams" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "segmentCount" INTEGER NOT NULL DEFAULT 3,
    "hostIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "owner" TEXT NOT NULL DEFAULT 'listener',
    "lastAutoGeneratedDate" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Podcast_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "Podcast_cadence_idx" ON "Podcast"("cadence");

ALTER TABLE "Episode" ADD COLUMN IF NOT EXISTS "podcastId" TEXT;

CREATE INDEX IF NOT EXISTS "Episode_podcastId_idx" ON "Episode"("podcastId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Episode_podcastId_fkey'
  ) THEN
    ALTER TABLE "Episode" ADD CONSTRAINT "Episode_podcastId_fkey"
      FOREIGN KEY ("podcastId") REFERENCES "Podcast"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- ---- Seed leagues (no-ops when the league already exists) ----
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('NFL', 'National Football League', 'Football', 'nfl', true) ON CONFLICT DO NOTHING;
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('NBA', 'National Basketball Association', 'Basketball', 'nba', true) ON CONFLICT DO NOTHING;
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('MLB', 'Major League Baseball', 'Baseball', 'mlb', true) ON CONFLICT DO NOTHING;
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('NHL', 'National Hockey League', 'Hockey', 'nhl', true) ON CONFLICT DO NOTHING;
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('NCAAF', 'College Football', 'Football', 'college-football', true) ON CONFLICT DO NOTHING;
INSERT INTO "League" ("id", "name", "sport", "slug", "isActive") VALUES ('NCAAB', 'College Basketball', 'Basketball', 'college-basketball', true) ON CONFLICT DO NOTHING;

-- ---- Seed teams (271 rows) ----
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:ari', 'NFL', 'Arizona Cardinals', 'Arizona', 'ARI', 'nfl-arizona-cardinals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:atl', 'NFL', 'Atlanta Falcons', 'Atlanta', 'ATL', 'nfl-atlanta-falcons-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:bal', 'NFL', 'Baltimore Ravens', 'Baltimore', 'BAL', 'nfl-baltimore-ravens-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:buf', 'NFL', 'Buffalo Bills', 'Buffalo', 'BUF', 'nfl-buffalo-bills-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:car', 'NFL', 'Carolina Panthers', 'Carolina', 'CAR', 'nfl-carolina-panthers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:chi', 'NFL', 'Chicago Bears', 'Chicago', 'CHI', 'nfl-chicago-bears-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:cin', 'NFL', 'Cincinnati Bengals', 'Cincinnati', 'CIN', 'nfl-cincinnati-bengals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:cle', 'NFL', 'Cleveland Browns', 'Cleveland', 'CLE', 'nfl-cleveland-browns-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:dal', 'NFL', 'Dallas Cowboys', 'Dallas', 'DAL', 'nfl-dallas-cowboys-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:den', 'NFL', 'Denver Broncos', 'Denver', 'DEN', 'nfl-denver-broncos-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:det', 'NFL', 'Detroit Lions', 'Detroit', 'DET', 'nfl-detroit-lions-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:gb', 'NFL', 'Green Bay Packers', 'Green Bay', 'GB', 'nfl-green-bay-packers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:hou', 'NFL', 'Houston Texans', 'Houston', 'HOU', 'nfl-houston-texans-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:ind', 'NFL', 'Indianapolis Colts', 'Indianapolis', 'IND', 'nfl-indianapolis-colts-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:jax', 'NFL', 'Jacksonville Jaguars', 'Jacksonville', 'JAX', 'nfl-jacksonville-jaguars-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:kc', 'NFL', 'Kansas City Chiefs', 'Kansas City', 'KC', 'nfl-kansas-city-chiefs-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:lv', 'NFL', 'Las Vegas Raiders', 'Las Vegas', 'LV', 'nfl-las-vegas-raiders-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:lac', 'NFL', 'Los Angeles Chargers', 'Los Angeles', 'LAC', 'nfl-los-angeles-chargers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:lar', 'NFL', 'Los Angeles Rams', 'Los Angeles', 'LAR', 'nfl-los-angeles-rams-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:mia', 'NFL', 'Miami Dolphins', 'Miami', 'MIA', 'nfl-miami-dolphins-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:min', 'NFL', 'Minnesota Vikings', 'Minnesota', 'MIN', 'nfl-minnesota-vikings-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:ne', 'NFL', 'New England Patriots', 'New England', 'NE', 'nfl-new-england-patriots-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:no', 'NFL', 'New Orleans Saints', 'New Orleans', 'NO', 'nfl-new-orleans-saints-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:nyg', 'NFL', 'New York Giants', 'New York', 'NYG', 'nfl-new-york-giants-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:nyj', 'NFL', 'New York Jets', 'New York', 'NYJ', 'nfl-new-york-jets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:phi', 'NFL', 'Philadelphia Eagles', 'Philadelphia', 'PHI', 'nfl-philadelphia-eagles-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:pit', 'NFL', 'Pittsburgh Steelers', 'Pittsburgh', 'PIT', 'nfl-pittsburgh-steelers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:sea', 'NFL', 'Seattle Seahawks', 'Seattle', 'SEA', 'nfl-seattle-seahawks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:sf', 'NFL', 'San Francisco 49ers', 'San Francisco', 'SF', 'nfl-san-francisco-49ers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:tb', 'NFL', 'Tampa Bay Buccaneers', 'Tampa Bay', 'TB', 'nfl-tampa-bay-buccaneers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:ten', 'NFL', 'Tennessee Titans', 'Tennessee', 'TEN', 'nfl-tennessee-titans-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nfl:was', 'NFL', 'Washington Commanders', 'Washington', 'WAS', 'nfl-washington-commanders-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:atl', 'NBA', 'Atlanta Hawks', 'Atlanta', 'ATL', 'nba-atlanta-hawks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:bos', 'NBA', 'Boston Celtics', 'Boston', 'BOS', 'nba-boston-celtics-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:bkn', 'NBA', 'Brooklyn Nets', 'Brooklyn', 'BKN', 'nba-brooklyn-nets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:cha', 'NBA', 'Charlotte Hornets', 'Charlotte', 'CHA', 'nba-charlotte-hornets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:chi', 'NBA', 'Chicago Bulls', 'Chicago', 'CHI', 'nba-chicago-bulls-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:cle', 'NBA', 'Cleveland Cavaliers', 'Cleveland', 'CLE', 'nba-cleveland-cavaliers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:dal', 'NBA', 'Dallas Mavericks', 'Dallas', 'DAL', 'nba-dallas-mavericks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:den', 'NBA', 'Denver Nuggets', 'Denver', 'DEN', 'nba-denver-nuggets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:det', 'NBA', 'Detroit Pistons', 'Detroit', 'DET', 'nba-detroit-pistons-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:gsw', 'NBA', 'Golden State Warriors', 'Golden State', 'GSW', 'nba-golden-state-warriors-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:hou', 'NBA', 'Houston Rockets', 'Houston', 'HOU', 'nba-houston-rockets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:ind', 'NBA', 'Indiana Pacers', 'Indiana', 'IND', 'nba-indiana-pacers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:lac', 'NBA', 'Los Angeles Clippers', 'Los Angeles', 'LAC', 'nba-los-angeles-clippers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:lal', 'NBA', 'Los Angeles Lakers', 'Los Angeles', 'LAL', 'nba-los-angeles-lakers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:mem', 'NBA', 'Memphis Grizzlies', 'Memphis', 'MEM', 'nba-memphis-grizzlies-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:mia', 'NBA', 'Miami Heat', 'Miami', 'MIA', 'nba-miami-heat-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:mil', 'NBA', 'Milwaukee Bucks', 'Milwaukee', 'MIL', 'nba-milwaukee-bucks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:min', 'NBA', 'Minnesota Timberwolves', 'Minnesota', 'MIN', 'nba-minnesota-timberwolves-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:nop', 'NBA', 'New Orleans Pelicans', 'New Orleans', 'NOP', 'nba-new-orleans-pelicans-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:nyk', 'NBA', 'New York Knicks', 'New York', 'NYK', 'nba-new-york-knicks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:okc', 'NBA', 'Oklahoma City Thunder', 'Oklahoma City', 'OKC', 'nba-oklahoma-city-thunder-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:orl', 'NBA', 'Orlando Magic', 'Orlando', 'ORL', 'nba-orlando-magic-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:phi', 'NBA', 'Philadelphia 76ers', 'Philadelphia', 'PHI', 'nba-philadelphia-76ers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:phx', 'NBA', 'Phoenix Suns', 'Phoenix', 'PHX', 'nba-phoenix-suns-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:por', 'NBA', 'Portland Trail Blazers', 'Portland', 'POR', 'nba-portland-trail-blazers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:sac', 'NBA', 'Sacramento Kings', 'Sacramento', 'SAC', 'nba-sacramento-kings-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:sas', 'NBA', 'San Antonio Spurs', 'San Antonio', 'SAS', 'nba-san-antonio-spurs-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:tor', 'NBA', 'Toronto Raptors', 'Toronto', 'TOR', 'nba-toronto-raptors-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:uta', 'NBA', 'Utah Jazz', 'Utah', 'UTA', 'nba-utah-jazz-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nba:was', 'NBA', 'Washington Wizards', 'Washington', 'WAS', 'nba-washington-wizards-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:ari', 'MLB', 'Arizona Diamondbacks', 'Arizona', 'ARI', 'mlb-arizona-diamondbacks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:atl', 'MLB', 'Atlanta Braves', 'Atlanta', 'ATL', 'mlb-atlanta-braves-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:bal', 'MLB', 'Baltimore Orioles', 'Baltimore', 'BAL', 'mlb-baltimore-orioles-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:bos', 'MLB', 'Boston Red Sox', 'Boston', 'BOS', 'mlb-boston-red-sox-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:chc', 'MLB', 'Chicago Cubs', 'Chicago', 'CHC', 'mlb-chicago-cubs-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:cws', 'MLB', 'Chicago White Sox', 'Chicago', 'CWS', 'mlb-chicago-white-sox-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:cin', 'MLB', 'Cincinnati Reds', 'Cincinnati', 'CIN', 'mlb-cincinnati-reds-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:cle', 'MLB', 'Cleveland Guardians', 'Cleveland', 'CLE', 'mlb-cleveland-guardians-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:col', 'MLB', 'Colorado Rockies', 'Colorado', 'COL', 'mlb-colorado-rockies-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:det', 'MLB', 'Detroit Tigers', 'Detroit', 'DET', 'mlb-detroit-tigers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:hou', 'MLB', 'Houston Astros', 'Houston', 'HOU', 'mlb-houston-astros-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:kc', 'MLB', 'Kansas City Royals', 'Kansas City', 'KC', 'mlb-kansas-city-royals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:laa', 'MLB', 'Los Angeles Angels', 'Los Angeles', 'LAA', 'mlb-los-angeles-angels-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:lad', 'MLB', 'Los Angeles Dodgers', 'Los Angeles', 'LAD', 'mlb-los-angeles-dodgers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:mia', 'MLB', 'Miami Marlins', 'Miami', 'MIA', 'mlb-miami-marlins-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:mil', 'MLB', 'Milwaukee Brewers', 'Milwaukee', 'MIL', 'mlb-milwaukee-brewers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:min', 'MLB', 'Minnesota Twins', 'Minnesota', 'MIN', 'mlb-minnesota-twins-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:nym', 'MLB', 'New York Mets', 'New York', 'NYM', 'mlb-new-york-mets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:nyy', 'MLB', 'New York Yankees', 'New York', 'NYY', 'mlb-new-york-yankees-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:ath', 'MLB', 'Sacramento Athletics', 'Sacramento', 'ATH', 'mlb-sacramento-athletics-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:phi', 'MLB', 'Philadelphia Phillies', 'Philadelphia', 'PHI', 'mlb-philadelphia-phillies-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:pit', 'MLB', 'Pittsburgh Pirates', 'Pittsburgh', 'PIT', 'mlb-pittsburgh-pirates-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:sd', 'MLB', 'San Diego Padres', 'San Diego', 'SD', 'mlb-san-diego-padres-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:sf', 'MLB', 'San Francisco Giants', 'San Francisco', 'SF', 'mlb-san-francisco-giants-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:sea', 'MLB', 'Seattle Mariners', 'Seattle', 'SEA', 'mlb-seattle-mariners-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:stl', 'MLB', 'St. Louis Cardinals', 'St. Louis', 'STL', 'mlb-st-louis-cardinals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:tb', 'MLB', 'Tampa Bay Rays', 'Tampa Bay', 'TB', 'mlb-tampa-bay-rays-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:tex', 'MLB', 'Texas Rangers', 'Texas', 'TEX', 'mlb-texas-rangers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:tor', 'MLB', 'Toronto Blue Jays', 'Toronto', 'TOR', 'mlb-toronto-blue-jays-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:mlb:wsh', 'MLB', 'Washington Nationals', 'Washington', 'WSH', 'mlb-washington-nationals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:ana', 'NHL', 'Anaheim Ducks', 'Anaheim', 'ANA', 'nhl-anaheim-ducks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:bos', 'NHL', 'Boston Bruins', 'Boston', 'BOS', 'nhl-boston-bruins-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:buf', 'NHL', 'Buffalo Sabres', 'Buffalo', 'BUF', 'nhl-buffalo-sabres-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:cgy', 'NHL', 'Calgary Flames', 'Calgary', 'CGY', 'nhl-calgary-flames-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:car', 'NHL', 'Carolina Hurricanes', 'Carolina', 'CAR', 'nhl-carolina-hurricanes-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:chi', 'NHL', 'Chicago Blackhawks', 'Chicago', 'CHI', 'nhl-chicago-blackhawks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:col', 'NHL', 'Colorado Avalanche', 'Colorado', 'COL', 'nhl-colorado-avalanche-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:cbj', 'NHL', 'Columbus Blue Jackets', 'Columbus', 'CBJ', 'nhl-columbus-blue-jackets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:dal', 'NHL', 'Dallas Stars', 'Dallas', 'DAL', 'nhl-dallas-stars-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:det', 'NHL', 'Detroit Red Wings', 'Detroit', 'DET', 'nhl-detroit-red-wings-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:edm', 'NHL', 'Edmonton Oilers', 'Edmonton', 'EDM', 'nhl-edmonton-oilers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:fla', 'NHL', 'Florida Panthers', 'Florida', 'FLA', 'nhl-florida-panthers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:lak', 'NHL', 'Los Angeles Kings', 'Los Angeles', 'LAK', 'nhl-los-angeles-kings-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:min', 'NHL', 'Minnesota Wild', 'Minnesota', 'MIN', 'nhl-minnesota-wild-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:mtl', 'NHL', 'Montreal Canadiens', 'Montreal', 'MTL', 'nhl-montreal-canadiens-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:nsh', 'NHL', 'Nashville Predators', 'Nashville', 'NSH', 'nhl-nashville-predators-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:njd', 'NHL', 'New Jersey Devils', 'New Jersey', 'NJD', 'nhl-new-jersey-devils-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:nyi', 'NHL', 'New York Islanders', 'New York', 'NYI', 'nhl-new-york-islanders-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:nyr', 'NHL', 'New York Rangers', 'New York', 'NYR', 'nhl-new-york-rangers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:ott', 'NHL', 'Ottawa Senators', 'Ottawa', 'OTT', 'nhl-ottawa-senators-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:phi', 'NHL', 'Philadelphia Flyers', 'Philadelphia', 'PHI', 'nhl-philadelphia-flyers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:pit', 'NHL', 'Pittsburgh Penguins', 'Pittsburgh', 'PIT', 'nhl-pittsburgh-penguins-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:sjs', 'NHL', 'San Jose Sharks', 'San Jose', 'SJS', 'nhl-san-jose-sharks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:sea', 'NHL', 'Seattle Kraken', 'Seattle', 'SEA', 'nhl-seattle-kraken-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:stl', 'NHL', 'St. Louis Blues', 'St. Louis', 'STL', 'nhl-st-louis-blues-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:tbl', 'NHL', 'Tampa Bay Lightning', 'Tampa Bay', 'TBL', 'nhl-tampa-bay-lightning-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:tor', 'NHL', 'Toronto Maple Leafs', 'Toronto', 'TOR', 'nhl-toronto-maple-leafs-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:uta', 'NHL', 'Utah Mammoth', 'Utah', 'UTA', 'nhl-utah-mammoth-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:van', 'NHL', 'Vancouver Canucks', 'Vancouver', 'VAN', 'nhl-vancouver-canucks-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:vgk', 'NHL', 'Vegas Golden Knights', 'Vegas', 'VGK', 'nhl-vegas-golden-knights-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:wsh', 'NHL', 'Washington Capitals', 'Washington', 'WSH', 'nhl-washington-capitals-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:nhl:wpg', 'NHL', 'Winnipeg Jets', 'Winnipeg', 'WPG', 'nhl-winnipeg-jets-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ala', 'NCAAF', 'Alabama', '', 'ALA', 'ncaaf-alabama-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ark', 'NCAAF', 'Arkansas', '', 'ARK', 'ncaaf-arkansas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:aub', 'NCAAF', 'Auburn', '', 'AUB', 'ncaaf-auburn-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:fla', 'NCAAF', 'Florida', '', 'FLA', 'ncaaf-florida-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:uga', 'NCAAF', 'Georgia', '', 'UGA', 'ncaaf-georgia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:uk', 'NCAAF', 'Kentucky', '', 'UK', 'ncaaf-kentucky-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:lsu', 'NCAAF', 'LSU', '', 'LSU', 'ncaaf-lsu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:miss', 'NCAAF', 'Ole Miss', '', 'MISS', 'ncaaf-ole-miss-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:msst', 'NCAAF', 'Mississippi State', '', 'MSST', 'ncaaf-mississippi-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:miz', 'NCAAF', 'Missouri', '', 'MIZ', 'ncaaf-missouri-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ou', 'NCAAF', 'Oklahoma', '', 'OU', 'ncaaf-oklahoma-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:scar', 'NCAAF', 'South Carolina', '', 'SCAR', 'ncaaf-south-carolina-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:tenn', 'NCAAF', 'Tennessee', '', 'TENN', 'ncaaf-tennessee-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:tex', 'NCAAF', 'Texas', '', 'TEX', 'ncaaf-texas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:tamu', 'NCAAF', 'Texas A&M', '', 'TAMU', 'ncaaf-texas-a-m-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:van', 'NCAAF', 'Vanderbilt', '', 'VAN', 'ncaaf-vanderbilt-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ill', 'NCAAF', 'Illinois', '', 'ILL', 'ncaaf-illinois-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:iu', 'NCAAF', 'Indiana', '', 'IU', 'ncaaf-indiana-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:iowa', 'NCAAF', 'Iowa', '', 'IOWA', 'ncaaf-iowa-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:umd', 'NCAAF', 'Maryland', '', 'UMD', 'ncaaf-maryland-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:mich', 'NCAAF', 'Michigan', '', 'MICH', 'ncaaf-michigan-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:msu', 'NCAAF', 'Michigan State', '', 'MSU', 'ncaaf-michigan-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:minn', 'NCAAF', 'Minnesota', '', 'MINN', 'ncaaf-minnesota-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:neb', 'NCAAF', 'Nebraska', '', 'NEB', 'ncaaf-nebraska-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:nw', 'NCAAF', 'Northwestern', '', 'NW', 'ncaaf-northwestern-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:osu', 'NCAAF', 'Ohio State', '', 'OSU', 'ncaaf-ohio-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ore', 'NCAAF', 'Oregon', '', 'ORE', 'ncaaf-oregon-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:psu', 'NCAAF', 'Penn State', '', 'PSU', 'ncaaf-penn-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:pur', 'NCAAF', 'Purdue', '', 'PUR', 'ncaaf-purdue-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:rut', 'NCAAF', 'Rutgers', '', 'RUT', 'ncaaf-rutgers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ucla', 'NCAAF', 'UCLA', '', 'UCLA', 'ncaaf-ucla-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:usc', 'NCAAF', 'USC', '', 'USC', 'ncaaf-usc-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:wash', 'NCAAF', 'Washington', '', 'WASH', 'ncaaf-washington-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:wis', 'NCAAF', 'Wisconsin', '', 'WIS', 'ncaaf-wisconsin-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ariz', 'NCAAF', 'Arizona', '', 'ARIZ', 'ncaaf-arizona-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:asu', 'NCAAF', 'Arizona State', '', 'ASU', 'ncaaf-arizona-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:bay', 'NCAAF', 'Baylor', '', 'BAY', 'ncaaf-baylor-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:byu', 'NCAAF', 'BYU', '', 'BYU', 'ncaaf-byu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:cin', 'NCAAF', 'Cincinnati', '', 'CIN', 'ncaaf-cincinnati-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:colo', 'NCAAF', 'Colorado', '', 'COLO', 'ncaaf-colorado-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:hou', 'NCAAF', 'Houston', '', 'HOU', 'ncaaf-houston-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:isu', 'NCAAF', 'Iowa State', '', 'ISU', 'ncaaf-iowa-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ku', 'NCAAF', 'Kansas', '', 'KU', 'ncaaf-kansas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ksu', 'NCAAF', 'Kansas State', '', 'KSU', 'ncaaf-kansas-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:okst', 'NCAAF', 'Oklahoma State', '', 'OKST', 'ncaaf-oklahoma-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:tcu', 'NCAAF', 'TCU', '', 'TCU', 'ncaaf-tcu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ttu', 'NCAAF', 'Texas Tech', '', 'TTU', 'ncaaf-texas-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ucf', 'NCAAF', 'UCF', '', 'UCF', 'ncaaf-ucf-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:utah', 'NCAAF', 'Utah', '', 'UTAH', 'ncaaf-utah-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:wvu', 'NCAAF', 'West Virginia', '', 'WVU', 'ncaaf-west-virginia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:bc', 'NCAAF', 'Boston College', '', 'BC', 'ncaaf-boston-college-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:cal', 'NCAAF', 'California', '', 'CAL', 'ncaaf-california-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:clem', 'NCAAF', 'Clemson', '', 'CLEM', 'ncaaf-clemson-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:duke', 'NCAAF', 'Duke', '', 'DUKE', 'ncaaf-duke-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:fsu', 'NCAAF', 'Florida State', '', 'FSU', 'ncaaf-florida-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:gt', 'NCAAF', 'Georgia Tech', '', 'GT', 'ncaaf-georgia-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:lou', 'NCAAF', 'Louisville', '', 'LOU', 'ncaaf-louisville-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:mia', 'NCAAF', 'Miami', '', 'MIA', 'ncaaf-miami-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:unc', 'NCAAF', 'North Carolina', '', 'UNC', 'ncaaf-north-carolina-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:ncst', 'NCAAF', 'NC State', '', 'NCST', 'ncaaf-nc-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:pitt', 'NCAAF', 'Pittsburgh', '', 'PITT', 'ncaaf-pittsburgh-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:smu', 'NCAAF', 'SMU', '', 'SMU', 'ncaaf-smu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:stan', 'NCAAF', 'Stanford', '', 'STAN', 'ncaaf-stanford-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:syr', 'NCAAF', 'Syracuse', '', 'SYR', 'ncaaf-syracuse-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:uva', 'NCAAF', 'Virginia', '', 'UVA', 'ncaaf-virginia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:vt', 'NCAAF', 'Virginia Tech', '', 'VT', 'ncaaf-virginia-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:wake', 'NCAAF', 'Wake Forest', '', 'WAKE', 'ncaaf-wake-forest-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaaf:nd', 'NCAAF', 'Notre Dame', '', 'ND', 'ncaaf-notre-dame-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ala', 'NCAAB', 'Alabama', '', 'ALA', 'ncaab-alabama-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ark', 'NCAAB', 'Arkansas', '', 'ARK', 'ncaab-arkansas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:aub', 'NCAAB', 'Auburn', '', 'AUB', 'ncaab-auburn-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:fla', 'NCAAB', 'Florida', '', 'FLA', 'ncaab-florida-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:uga', 'NCAAB', 'Georgia', '', 'UGA', 'ncaab-georgia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:uk', 'NCAAB', 'Kentucky', '', 'UK', 'ncaab-kentucky-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:lsu', 'NCAAB', 'LSU', '', 'LSU', 'ncaab-lsu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:miss', 'NCAAB', 'Ole Miss', '', 'MISS', 'ncaab-ole-miss-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:msst', 'NCAAB', 'Mississippi State', '', 'MSST', 'ncaab-mississippi-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:miz', 'NCAAB', 'Missouri', '', 'MIZ', 'ncaab-missouri-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ou', 'NCAAB', 'Oklahoma', '', 'OU', 'ncaab-oklahoma-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:scar', 'NCAAB', 'South Carolina', '', 'SCAR', 'ncaab-south-carolina-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:tenn', 'NCAAB', 'Tennessee', '', 'TENN', 'ncaab-tennessee-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:tex', 'NCAAB', 'Texas', '', 'TEX', 'ncaab-texas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:tamu', 'NCAAB', 'Texas A&M', '', 'TAMU', 'ncaab-texas-a-m-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:van', 'NCAAB', 'Vanderbilt', '', 'VAN', 'ncaab-vanderbilt-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ill', 'NCAAB', 'Illinois', '', 'ILL', 'ncaab-illinois-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:iu', 'NCAAB', 'Indiana', '', 'IU', 'ncaab-indiana-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:iowa', 'NCAAB', 'Iowa', '', 'IOWA', 'ncaab-iowa-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:umd', 'NCAAB', 'Maryland', '', 'UMD', 'ncaab-maryland-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:mich', 'NCAAB', 'Michigan', '', 'MICH', 'ncaab-michigan-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:msu', 'NCAAB', 'Michigan State', '', 'MSU', 'ncaab-michigan-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:minn', 'NCAAB', 'Minnesota', '', 'MINN', 'ncaab-minnesota-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:neb', 'NCAAB', 'Nebraska', '', 'NEB', 'ncaab-nebraska-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:nw', 'NCAAB', 'Northwestern', '', 'NW', 'ncaab-northwestern-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:osu', 'NCAAB', 'Ohio State', '', 'OSU', 'ncaab-ohio-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ore', 'NCAAB', 'Oregon', '', 'ORE', 'ncaab-oregon-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:psu', 'NCAAB', 'Penn State', '', 'PSU', 'ncaab-penn-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:pur', 'NCAAB', 'Purdue', '', 'PUR', 'ncaab-purdue-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:rut', 'NCAAB', 'Rutgers', '', 'RUT', 'ncaab-rutgers-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ucla', 'NCAAB', 'UCLA', '', 'UCLA', 'ncaab-ucla-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:usc', 'NCAAB', 'USC', '', 'USC', 'ncaab-usc-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:wash', 'NCAAB', 'Washington', '', 'WASH', 'ncaab-washington-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:wis', 'NCAAB', 'Wisconsin', '', 'WIS', 'ncaab-wisconsin-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ariz', 'NCAAB', 'Arizona', '', 'ARIZ', 'ncaab-arizona-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:asu', 'NCAAB', 'Arizona State', '', 'ASU', 'ncaab-arizona-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:bay', 'NCAAB', 'Baylor', '', 'BAY', 'ncaab-baylor-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:byu', 'NCAAB', 'BYU', '', 'BYU', 'ncaab-byu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:cin', 'NCAAB', 'Cincinnati', '', 'CIN', 'ncaab-cincinnati-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:colo', 'NCAAB', 'Colorado', '', 'COLO', 'ncaab-colorado-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:hou', 'NCAAB', 'Houston', '', 'HOU', 'ncaab-houston-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:isu', 'NCAAB', 'Iowa State', '', 'ISU', 'ncaab-iowa-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ku', 'NCAAB', 'Kansas', '', 'KU', 'ncaab-kansas-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ksu', 'NCAAB', 'Kansas State', '', 'KSU', 'ncaab-kansas-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:okst', 'NCAAB', 'Oklahoma State', '', 'OKST', 'ncaab-oklahoma-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:tcu', 'NCAAB', 'TCU', '', 'TCU', 'ncaab-tcu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ttu', 'NCAAB', 'Texas Tech', '', 'TTU', 'ncaab-texas-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ucf', 'NCAAB', 'UCF', '', 'UCF', 'ncaab-ucf-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:utah', 'NCAAB', 'Utah', '', 'UTAH', 'ncaab-utah-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:wvu', 'NCAAB', 'West Virginia', '', 'WVU', 'ncaab-west-virginia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:bc', 'NCAAB', 'Boston College', '', 'BC', 'ncaab-boston-college-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:cal', 'NCAAB', 'California', '', 'CAL', 'ncaab-california-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:clem', 'NCAAB', 'Clemson', '', 'CLEM', 'ncaab-clemson-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:duke', 'NCAAB', 'Duke', '', 'DUKE', 'ncaab-duke-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:fsu', 'NCAAB', 'Florida State', '', 'FSU', 'ncaab-florida-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:gt', 'NCAAB', 'Georgia Tech', '', 'GT', 'ncaab-georgia-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:lou', 'NCAAB', 'Louisville', '', 'LOU', 'ncaab-louisville-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:mia', 'NCAAB', 'Miami', '', 'MIA', 'ncaab-miami-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:unc', 'NCAAB', 'North Carolina', '', 'UNC', 'ncaab-north-carolina-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:ncst', 'NCAAB', 'NC State', '', 'NCST', 'ncaab-nc-state-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:pitt', 'NCAAB', 'Pittsburgh', '', 'PITT', 'ncaab-pittsburgh-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:smu', 'NCAAB', 'SMU', '', 'SMU', 'ncaab-smu-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:stan', 'NCAAB', 'Stanford', '', 'STAN', 'ncaab-stanford-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:syr', 'NCAAB', 'Syracuse', '', 'SYR', 'ncaab-syracuse-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:uva', 'NCAAB', 'Virginia', '', 'UVA', 'ncaab-virginia-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:vt', 'NCAAB', 'Virginia Tech', '', 'VT', 'ncaab-virginia-tech-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:wake', 'NCAAB', 'Wake Forest', '', 'WAKE', 'ncaab-wake-forest-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:nd', 'NCAAB', 'Notre Dame', '', 'ND', 'ncaab-notre-dame-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:uconn', 'NCAAB', 'UConn', '', 'UCONN', 'ncaab-uconn-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:nova', 'NCAAB', 'Villanova', '', 'NOVA', 'ncaab-villanova-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:gtwn', 'NCAAB', 'Georgetown', '', 'GTWN', 'ncaab-georgetown-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:crei', 'NCAAB', 'Creighton', '', 'CREI', 'ncaab-creighton-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:marq', 'NCAAB', 'Marquette', '', 'MARQ', 'ncaab-marquette-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:xav', 'NCAAB', 'Xavier', '', 'XAV', 'ncaab-xavier-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:but', 'NCAAB', 'Butler', '', 'BUT', 'ncaab-butler-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:prov', 'NCAAB', 'Providence', '', 'PROV', 'ncaab-providence-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:sju', 'NCAAB', 'St. John''s', '', 'SJU', 'ncaab-st-john-s-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:hall', 'NCAAB', 'Seton Hall', '', 'HALL', 'ncaab-seton-hall-seed') ON CONFLICT DO NOTHING;
INSERT INTO "Team" ("id", "leagueId", "name", "city", "abbreviation", "slug") VALUES ('seed:ncaab:dep', 'NCAAB', 'DePaul', '', 'DEP', 'ncaab-depaul-seed') ON CONFLICT DO NOTHING;
