// Publish-time assets that the content pipeline doesn't already produce:
// argument-forward TITLE OPTIONS and a bold COVER ART image, plus the
// compliance-critical injection of the responsible-gambling disclaimer into a
// betting episode's show notes. Show notes / chapters / transcript are already
// generated by contentAssetService (content_ready) — we reuse those and only
// add what's missing.

import { db } from "@/lib/db";
import { getStorageProvider } from "@/lib/providers/storage/factory";
import {
  episodeHasBettingContent,
  hasResponsibleGamblingDisclaimer,
  RESPONSIBLE_GAMBLING_DISCLAIMER,
  checkGamblingCompliance,
  type GamblingComplianceResult,
} from "./compliance";

const clip = (s: string, n = 60) => (s.length <= n ? s : s.slice(0, n - 1).trimEnd() + "…");
const subjectOf = (title: string) => title.replace(/[?!.]+$/g, "").replace(/^(is|are|will|should|can|do|does|why|how)\s+/i, "").trim();

/** Argument-forward title candidates (≤~60 chars) derived from the episode's
 *  real debate topics. Deterministic — no LLM needed. */
export function generateTitleOptions(episodeTitle: string, topicTitles: string[]): string[] {
  const out: string[] = [];
  const push = (t: string) => {
    const v = clip(t.trim());
    if (v.length >= 8 && !out.some((o) => o.toLowerCase() === v.toLowerCase())) out.push(v);
  };
  // The topics are already takes — surface them verbatim first.
  for (const t of topicTitles) push(t);
  const lead = subjectOf(topicTitles[0] || episodeTitle || "");
  if (lead) {
    push(`${lead}: settle it`);
    push(`The truth about ${lead}`);
    push(`Nobody wants to say it about ${lead}`);
  }
  push(episodeTitle);
  return out.slice(0, 5);
}

function wrapForCover(text: string, maxChars: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > maxChars && cur) {
      lines.push(cur);
      cur = w;
      if (lines.length === maxLines - 1) break;
    } else {
      cur = (cur + " " + w).trim();
    }
  }
  if (cur && lines.length < maxLines) lines.push(cur);
  if (lines.length === maxLines && words.length > lines.join(" ").split(/\s+/).length) {
    lines[maxLines - 1] = clip(lines[maxLines - 1], maxChars);
  }
  return lines;
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Bold, high-contrast, orange-forward, thumbnail-legible cover art. Carbon
 * ground, a Signal-Orange band, and the title set large. The SVG is the vector
 * source of truth; it is rasterised to a directory-compliant PNG by
 * {@link rasterizeCoverArtPng} before storage (Apple/Spotify require JPEG/PNG,
 * 1400–3000px, RGB), while the SVG itself is kept alongside as the editable
 * source.
 */
export function generateCoverArtSvg(title: string, tag: string): string {
  const S = 1500;
  const lines = wrapForCover(title.toUpperCase(), 15, 3);
  const fontSize = lines.length >= 3 ? 150 : lines.length === 2 ? 185 : 220;
  const blockH = lines.length * fontSize * 1.05;
  const startY = S / 2 - blockH / 2 + fontSize * 0.8;
  const textEls = lines
    .map((ln, i) => `<text x="110" y="${Math.round(startY + i * fontSize * 1.05)}" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="${fontSize}" fill="#EDEFF2">${xmlEscape(ln)}</text>`)
    .join("\n    ");
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">
  <rect width="${S}" height="${S}" fill="#0E1116"/>
  <rect x="0" y="0" width="${S}" height="24" fill="#FF5A1F"/>
  <rect x="0" y="${S - 340}" width="${S}" height="340" fill="#FF5A1F"/>
  <text x="110" y="${S - 200}" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="120" fill="#0E1116">TAKE MACHINE</text>
  <text x="110" y="${S - 90}" font-family="Arial, sans-serif" font-weight="700" font-size="70" fill="#0E1116">${xmlEscape(tag.toUpperCase())}</text>
  <circle cx="${S - 150}" cy="150" r="46" fill="#FF5A1F"/>
  ${textEls}
</svg>`;
}

// Directory requirements the raster output is built to satisfy:
//  - Apple Podcasts: square JPEG/PNG, 1400×1400 min, 3000×3000 max, RGB.
//  - Spotify: square JPEG/PNG, ≥1400×1400 (3000×3000 recommended).
// We render at the 3000×3000 maximum so a single asset satisfies both.
export const COVER_PNG_SIZE = 3000;
// YouTube (and other 16:9 surfaces) want a widescreen image; 1920×1080 is the
// standard, universally-accepted size. Best-effort — the square PNG is what the
// podcast directories consume.
export const COVER_16X9_WIDTH = 1920;
export const COVER_16X9_HEIGHT = 1080;
// Carbon ground — used to flatten any transparency and to pillarbox the 16:9.
const COVER_BG = "#0E1116";

/**
 * Rasterise the cover-art SVG to a square RGB PNG at {@link COVER_PNG_SIZE}
 * (3000×3000). Uses `sharp` (libvips/librsvg), which Next.js already ships and
 * auto-externalises for server code. `flatten` drops the alpha channel so the
 * result is a directory-safe RGB PNG (no alpha), and `png()` keeps it lossless.
 */
export async function rasterizeCoverArtPng(svg: string, size: number = COVER_PNG_SIZE): Promise<Buffer> {
  const { default: sharp } = await import("sharp");
  return sharp(Buffer.from(svg, "utf8"), { density: 96 })
    .resize(size, size, { fit: "fill" })
    .flatten({ background: COVER_BG })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/**
 * Rasterise the (square) cover art onto a 16:9 RGB PNG for YouTube-style
 * surfaces — the square art is centred on the carbon ground (pillarboxed). Best
 * effort; not consumed by the podcast RSS feed.
 */
export async function rasterizeCoverArt16x9(svg: string): Promise<Buffer> {
  const { default: sharp } = await import("sharp");
  return sharp(Buffer.from(svg, "utf8"), { density: 96 })
    .resize(COVER_16X9_WIDTH, COVER_16X9_HEIGHT, { fit: "contain", background: COVER_BG })
    .flatten({ background: COVER_BG })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

export interface EnsurePublishAssetsResult {
  ok: boolean;
  error?: string;
  betting: boolean;
  disclaimerAdded: boolean;
  coverArtUrl: string | null;
  titleOptions: string[];
  compliance: GamblingComplianceResult;
}

/**
 * Idempotent pre-publish asset pass: inject the responsible-gambling disclaimer
 * into a betting episode's show notes (if missing), generate + store cover art,
 * and compute title options. Reuses the episode's existing longShowNotes.
 */
export async function ensurePublishAssets(episodeId: string, opts?: { regenerateCover?: boolean }): Promise<EnsurePublishAssetsResult> {
  const episode = await db.episode.findUnique({
    where: { id: episodeId },
    include: {
      podcast: { select: { verticals: true } },
      topics: { orderBy: { orderIndex: "asc" }, include: { topic: { select: { title: true, summary: true, leagueId: true, bettingRelevanceScore: true, sport: true } } } },
    },
  });
  if (!episode) {
    return { ok: false, error: "Episode not found.", betting: false, disclaimerAdded: false, coverArtUrl: null, titleOptions: [], compliance: { betting: false, compliant: false, reasons: ["Episode not found."], prohibited: [], disclaimerPresent: false } };
  }

  const topicTitles = episode.topics.map((et) => et.topic?.title).filter(Boolean) as string[];
  const topics = episode.topics.map((et) => ({
    title: et.topic?.title ?? "",
    summary: et.topic?.summary ?? null,
    leagueId: et.topic?.leagueId ?? null,
    bettingRelevanceScore: et.topic?.bettingRelevanceScore ?? null,
  }));
  const betting = episodeHasBettingContent({ podcastVerticals: episode.podcast?.verticals ?? null, topics });

  // 1. Disclaimer injection for betting episodes.
  let notes = episode.longShowNotes ?? "";
  let disclaimerAdded = false;
  if (betting && !hasResponsibleGamblingDisclaimer(notes)) {
    notes = `${notes.trim()}\n\n${RESPONSIBLE_GAMBLING_DISCLAIMER}\n`;
    disclaimerAdded = true;
  }

  // 2. Cover art. Directories (Apple Podcasts, Spotify) require a rasterised
  //    JPEG/PNG — not SVG — so we keep the SVG as the vector source and publish
  //    a 3000×3000 RGB PNG as the feed image. Legacy episodes whose rssImageUrl
  //    still points at a `.svg` are auto-upgraded to the PNG on the next pass
  //    (additive: the SVG file is never removed, only the pointer improves).
  let coverArtUrl = episode.rssImageUrl ?? null;
  const isLegacySvg = !!coverArtUrl && coverArtUrl.toLowerCase().endsWith(".svg");
  if (!coverArtUrl || isLegacySvg || opts?.regenerateCover) {
    try {
      const tag = episode.topics[0]?.topic?.sport || episode.podcast?.verticals?.[0] || "Sports";
      const svg = generateCoverArtSvg(episode.title, tag);
      const storage = getStorageProvider();
      // Keep the editable vector source.
      await storage.putObject({
        key: `episodes/${episode.id}/cover.svg`,
        body: Buffer.from(svg, "utf8"),
        contentType: "image/svg+xml",
      });
      // The directory-facing asset: a 3000×3000 RGB PNG.
      const png = await rasterizeCoverArtPng(svg);
      const uploadedPng = await storage.putObject({
        key: `episodes/${episode.id}/cover.png`,
        body: png,
        contentType: "image/png",
      });
      coverArtUrl = uploadedPng.url;
      // Best-effort 16:9 for YouTube-style surfaces; failure here never blocks
      // the square PNG that the feed actually uses.
      try {
        const wide = await rasterizeCoverArt16x9(svg);
        await storage.putObject({
          key: `episodes/${episode.id}/cover-16x9.png`,
          body: wide,
          contentType: "image/png",
        });
      } catch {
        /* non-fatal: widescreen variant is optional */
      }
    } catch (err: any) {
      // Non-fatal: publishing doesn't require cover art; keep whatever we had.
      coverArtUrl = episode.rssImageUrl ?? null;
    }
  }

  // 3. Persist any changes.
  if (disclaimerAdded || coverArtUrl !== episode.rssImageUrl) {
    await db.episode.update({
      where: { id: episode.id },
      data: {
        ...(disclaimerAdded ? { longShowNotes: notes } : {}),
        ...(coverArtUrl && coverArtUrl !== episode.rssImageUrl ? { rssImageUrl: coverArtUrl } : {}),
      },
    });
  }

  const marketingText = [episode.title, episode.rssSummary, episode.description, notes].filter(Boolean).join("\n");
  const compliance = checkGamblingCompliance({ betting, showNotes: notes, marketingText });

  return {
    ok: true,
    betting,
    disclaimerAdded,
    coverArtUrl,
    titleOptions: generateTitleOptions(episode.title, topicTitles),
    compliance,
  };
}
