// Publish-time assets that the content pipeline doesn't already produce:
// argument-forward TITLE OPTIONS and a bold COVER ART image, plus the
// compliance-critical injection of the responsible-gambling disclaimer into a
// betting episode's show notes. Show notes / chapters / transcript are already
// generated by contentAssetService (content_ready) — we reuse those and only
// add what's missing.

import { db } from "@/lib/db";
import { getStorageProvider } from "@/lib/providers/storage/factory";
import {
  episodeHasBettingContent,
  hasResponsibleGamblingDisclaimer,
  RESPONSIBLE_GAMBLING_DISCLAIMER,
  checkGamblingCompliance,
  type GamblingComplianceResult,
} from "./compliance";

const clip = (s: string, n = 60) => (s.length <= n ? s : s.slice(0, n - 1).trimEnd() + "…");
const subjectOf = (title: string) => title.replace(/[?!.]+$/g, "").replace(/^(is|are|will|should|can|do|does|why|how)\s+/i, "").trim();

/** Argument-forward title candidates (≤~60 chars) derived from the episode's
 *  real debate topics. Deterministic — no LLM needed. */
export function generateTitleOptions(episodeTitle: string, topicTitles: string[]): string[] {
  const out: string[] = [];
  const push = (t: string) => {
    const v = clip(t.trim());
    if (v.length >= 8 && !out.some((o) => o.toLowerCase() === v.toLowerCase())) out.push(v);
  };
  // The topics are already takes — surface them verbatim first.
  for (const t of topicTitles) push(t);
  const lead = subjectOf(topicTitles[0] || episodeTitle || "");
  if (lead) {
    push(`${lead}: settle it`);
    push(`The truth about ${lead}`);
    push(`Nobody wants to say it about ${lead}`);
  }
  push(episodeTitle);
  return out.slice(0, 5);
}

function wrapForCover(text: string, maxChars: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > maxChars && cur) {
      lines.push(cur);
      cur = w;
      if (lines.length === maxLines - 1) break;
    } else {
      cur = (cur + " " + w).trim();
    }
  }
  if (cur && lines.length < maxLines) lines.push(cur);
  if (lines.length === maxLines && words.length > lines.join(" ").split(/\s+/).length) {
    lines[maxLines - 1] = clip(lines[maxLines - 1], maxChars);
  }
  return lines;
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Bold, high-contrast, orange-forward, thumbnail-legible cover art. Carbon
 * ground, a Signal-Orange band, and the title set large. Rendered as SVG (no
 * rasteriser is available in this environment — see the flagged limitation:
 * Apple Podcasts wants JPEG/PNG ≥1400px, so this should be rasterised before a
 * real store submission).
 */
export function generateCoverArtSvg(title: string, tag: string): string {
  const S = 1500;
  const lines = wrapForCover(title.toUpperCase(), 15, 3);
  const fontSize = lines.length >= 3 ? 150 : lines.length === 2 ? 185 : 220;
  const blockH = lines.length * fontSize * 1.05;
  const startY = S / 2 - blockH / 2 + fontSize * 0.8;
  const textEls = lines
    .map((ln, i) => `<text x="110" y="${Math.round(startY + i * fontSize * 1.05)}" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="${fontSize}" fill="#EDEFF2">${xmlEscape(ln)}</text>`)
    .join("\n    ");
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">
  <rect width="${S}" height="${S}" fill="#0E1116"/>
  <rect x="0" y="0" width="${S}" height="24" fill="#FF5A1F"/>
  <rect x="0" y="${S - 340}" width="${S}" height="340" fill="#FF5A1F"/>
  <text x="110" y="${S - 200}" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="120" fill="#0E1116">TAKE MACHINE</text>
  <text x="110" y="${S - 90}" font-family="Arial, sans-serif" font-weight="700" font-size="70" fill="#0E1116">${xmlEscape(tag.toUpperCase())}</text>
  <circle cx="${S - 150}" cy="150" r="46" fill="#FF5A1F"/>
  ${textEls}
</svg>`;
}

export interface EnsurePublishAssetsResult {
  ok: boolean;
  error?: string;
  betting: boolean;
  disclaimerAdded: boolean;
  coverArtUrl: string | null;
  titleOptions: string[];
  compliance: GamblingComplianceResult;
}

/**
 * Idempotent pre-publish asset pass: inject the responsible-gambling disclaimer
 * into a betting episode's show notes (if missing), generate + store cover art,
 * and compute title options. Reuses the episode's existing longShowNotes.
 */
export async function ensurePublishAssets(episodeId: string, opts?: { regenerateCover?: boolean }): Promise<EnsurePublishAssetsResult> {
  const episode = await db.episode.findUnique({
    where: { id: episodeId },
    include: {
      podcast: { select: { verticals: true } },
      topics: { orderBy: { orderIndex: "asc" }, include: { topic: { select: { title: true, summary: true, leagueId: true, bettingRelevanceScore: true, sport: true } } } },
    },
  });
  if (!episode) {
    return { ok: false, error: "Episode not found.", betting: false, disclaimerAdded: false, coverArtUrl: null, titleOptions: [], compliance: { betting: false, compliant: false, reasons: ["Episode not found."], prohibited: [], disclaimerPresent: false } };
  }

  const topicTitles = episode.topics.map((et) => et.topic?.title).filter(Boolean) as string[];
  const topics = episode.topics.map((et) => ({
    title: et.topic?.title ?? "",
    summary: et.topic?.summary ?? null,
    leagueId: et.topic?.leagueId ?? null,
    bettingRelevanceScore: et.topic?.bettingRelevanceScore ?? null,
  }));
  const betting = episodeHasBettingContent({ podcastVerticals: episode.podcast?.verticals ?? null, topics });

  // 1. Disclaimer injection for betting episodes.
  let notes = episode.longShowNotes ?? "";
  let disclaimerAdded = false;
  if (betting && !hasResponsibleGamblingDisclaimer(notes)) {
    notes = `${notes.trim()}\n\n${RESPONSIBLE_GAMBLING_DISCLAIMER}\n`;
    disclaimerAdded = true;
  }

  // 2. Cover art.
  let coverArtUrl = episode.rssImageUrl ?? null;
  if (!coverArtUrl || opts?.regenerateCover) {
    try {
      const tag = episode.topics[0]?.topic?.sport || episode.podcast?.verticals?.[0] || "Sports";
      const svg = generateCoverArtSvg(episode.title, tag);
      const storage = getStorageProvider();
      const uploaded = await storage.putObject({
        key: `episodes/${episode.id}/cover.svg`,
        body: Buffer.from(svg, "utf8"),
        contentType: "image/svg+xml",
      });
      coverArtUrl = uploaded.url;
    } catch (err: any) {
      // Non-fatal: publishing doesn't require cover art; surface via reasons.
      coverArtUrl = episode.rssImageUrl ?? null;
    }
  }

  // 3. Persist any changes.
  if (disclaimerAdded || coverArtUrl !== episode.rssImageUrl) {
    await db.episode.update({
      where: { id: episode.id },
      data: {
        ...(disclaimerAdded ? { longShowNotes: notes } : {}),
        ...(coverArtUrl && coverArtUrl !== episode.rssImageUrl ? { rssImageUrl: coverArtUrl } : {}),
      },
    });
  }

  const marketingText = [episode.title, episode.rssSummary, episode.description, notes].filter(Boolean).join("\n");
  const compliance = checkGamblingCompliance({ betting, showNotes: notes, marketingText });

  return {
    ok: true,
    betting,
    disclaimerAdded,
    coverArtUrl,
    titleOptions: generateTitleOptions(episode.title, topicTitles),
    compliance,
  };
}
