import { db } from "../db";
import { queueEpisodeBuildJob } from "../queue/podcastQueue";
import { teamLeagueIdsForVerticals } from "../verticals";

// Recurring podcast auto-generation. One daily scheduler tick (registered as
// a BullMQ job scheduler at worker boot) finds every recurring podcast whose
// scheduleDays includes today's weekday and enqueues an episode build from
// its saved config. Generation time is global and configurable via env —
// deliberately not a per-podcast picker yet.
//
// Idempotency is layered:
//  1. An atomic DB claim on Podcast.lastAutoGeneratedDate (updateMany with a
//     not-today guard) — re-running the scheduler the same day claims 0 rows.
//  2. A deterministic BullMQ jobId (recurring-<podcastId>-<date>) — even a
//     racing duplicate enqueue collapses into one job.

export {
  RECURRING_GENERATION_TIME,
  RECURRING_GENERATION_TZ,
  recurringCronPattern,
  schedulerDateParts,
} from "./recurringSchedule";
import { schedulerDateParts } from "./recurringSchedule";

export interface PodcastGenerationOutcome {
  podcastId: string;
  name: string;
  status: "enqueued" | "skipped_already_generated" | "failed";
  jobId?: string;
  error?: string;
}

/** Enqueue one episode build from a podcast's current saved config. */
export async function enqueueEpisodeBuildForPodcast(
  podcast: {
    id: string;
    name: string;
    verticals: string[];
    teams: string[];
    segmentCount: number;
  },
  opts?: { titleSuffix?: string; jobId?: string }
) {
  const teamNames =
    podcast.teams.length > 0
      ? (
          await db.team.findMany({ where: { id: { in: podcast.teams } }, select: { name: true } })
        ).map((t) => t.name)
      : [];
  const leagueIds = teamLeagueIdsForVerticals(podcast.verticals);

  return queueEpisodeBuildJob(
    {
      title: `${podcast.name}${opts?.titleSuffix ? ` — ${opts.titleSuffix}` : ""}`,
      description: `Generated from the "${podcast.name}" podcast configuration.`,
      podcastId: podcast.id,
      targetTopicCount: podcast.segmentCount,
      leagueIds: leagueIds.length > 0 ? leagueIds : undefined,
      teamNames: teamNames.length > 0 ? teamNames : undefined,
    },
    opts?.jobId ? { jobId: opts.jobId } : undefined
  );
}

export async function runRecurringPodcastGeneration(now: Date = new Date()) {
  const { dateKey, weekday } = schedulerDateParts(now);

  const due = await db.podcast.findMany({
    where: { cadence: "recurring", scheduleDays: { has: weekday } },
  });

  const outcomes: PodcastGenerationOutcome[] = [];
  for (const p of due) {
    try {
      // Atomic claim: only one runner per podcast per day wins this update.
      const claimed = await db.podcast.updateMany({
        where: {
          id: p.id,
          OR: [{ lastAutoGeneratedDate: null }, { lastAutoGeneratedDate: { not: dateKey } }],
        },
        data: { lastAutoGeneratedDate: dateKey },
      });
      if (claimed.count === 0) {
        outcomes.push({ podcastId: p.id, name: p.name, status: "skipped_already_generated" });
        continue;
      }

      const job = await enqueueEpisodeBuildForPodcast(p, {
        titleSuffix: dateKey,
        jobId: `recurring-${p.id}-${dateKey}`,
      });
      outcomes.push({ podcastId: p.id, name: p.name, status: "enqueued", jobId: String(job.id) });
    } catch (err: any) {
      outcomes.push({ podcastId: p.id, name: p.name, status: "failed", error: err.message });
    }
  }

  return { dateKey, weekday, dueCount: due.length, outcomes };
}
