export interface StatusUI {
  label: string;
  description: string;
  severity: "info" | "warning" | "success" | "danger";
  nextAction: string;
  badgeStyle: string;
}

const statusMap: Record<string, StatusUI> = {
  draft: {
    label: "Draft",
    description: "Initial state of the record, editing in progress.",
    severity: "info",
    nextAction: "Evaluate and approve for production.",
    badgeStyle: "background-color: #1e293b; color: #94a3b8; border: 1px solid #334155;",
  },
  queued: {
    label: "Queued",
    description: "Job is queued in background worker and waiting for execution.",
    severity: "warning",
    nextAction: "Wait for background worker to pickup.",
    badgeStyle: "background-color: #1e1b4b; color: #a5b4fc; border: 1px solid #312e81;",
  },
  generating: {
    label: "Generating",
    description: "Assets are currently being generated by the worker.",
    severity: "warning",
    nextAction: "Wait for generation process to complete.",
    badgeStyle: "background-color: #3b0764; color: #d8b4fe; border: 1px solid #581c87;",
  },
  completed: {
    label: "Completed",
    description: "Asset or step completed successfully.",
    severity: "success",
    nextAction: "Ready for the next pipeline stage.",
    badgeStyle: "background-color: #064e3b; color: #6ee7b7; border: 1px solid #065f46;",
  },
  failed: {
    label: "Failed",
    description: "An error occurred during worker execution.",
    severity: "danger",
    nextAction: "Inspect job logs and retry the step.",
    badgeStyle: "background-color: #4c0519; color: #fda4af; border: 1px solid #881337;",
  },
  rejected: {
    label: "Rejected",
    description: "Record has been rejected or marked as unusable.",
    severity: "danger",
    nextAction: "Revise content or choose another candidate.",
    badgeStyle: "background-color: #451a03; color: #fdba74; border: 1px solid #78350f;",
  },
  needs_revision: {
    label: "Needs Revision",
    description: "Issues detected that require manual revision.",
    severity: "warning",
    nextAction: "Edit details and update status.",
    badgeStyle: "background-color: #422006; color: #fef08a; border: 1px solid #713f12;",
  },
  script_draft: {
    label: "Script Draft",
    description: "Script drafted by LLM and undergoing review.",
    severity: "info",
    nextAction: "Perform fact-check verification.",
    badgeStyle: "background-color: #0c4a6e; color: #7dd3fc; border: 1px solid #0369a1;",
  },
  script_approved: {
    label: "Script Approved",
    description: "Script is approved and ready for audio segments processing.",
    severity: "success",
    nextAction: "Generate individual Audio Segments.",
    badgeStyle: "background-color: #14532d; color: #86efac; border: 1px solid #166534;",
  },
  fact_checked: {
    label: "Fact Checked",
    description: "Fact-checking run completed successfully.",
    severity: "success",
    nextAction: "Review fact check warnings and approve script.",
    badgeStyle: "background-color: #134e5e; color: #67e8f9; border: 1px solid #155e75;",
  },
  audio_segments_ready: {
    label: "Segments Ready",
    description: "All individual speech audio segments are generated.",
    severity: "success",
    nextAction: "Stitch audio segments with intro/outro.",
    badgeStyle: "background-color: #1e3a8a; color: #93c5fd; border: 1px solid #1e40af;",
  },
  audio_stitching: {
    label: "Audio Stitching",
    description: "Stitching audio segments into final episode audio.",
    severity: "warning",
    nextAction: "Wait for final MP3 build to complete.",
    badgeStyle: "background-color: #3b0764; color: #d8b4fe; border: 1px solid #581c87;",
  },
  audio_ready: {
    label: "Audio Ready",
    description: "Final stitched audio file is ready for listeners.",
    severity: "success",
    nextAction: "Generate transcripts, show notes and assets.",
    badgeStyle: "background-color: #14532d; color: #86efac; border: 1px solid #166534;",
  },
  content_generating: {
    label: "Content Generating",
    description: "Generating final listener assets in background.",
    severity: "warning",
    nextAction: "Wait for metadata & transcripts to save.",
    badgeStyle: "background-color: #3b0764; color: #d8b4fe; border: 1px solid #581c87;",
  },
  content_ready: {
    label: "Content Ready",
    description: "Transcript, chapters, metadata and show notes are ready.",
    severity: "success",
    nextAction: "Prepare RSS publishing configurations.",
    badgeStyle: "background-color: #064e3b; color: #6ee7b7; border: 1px solid #065f46;",
  },
  publish_ready: {
    label: "Publish Ready",
    description: "Permanent RSS metadata and Guid are assigned and ready.",
    severity: "success",
    nextAction: "Publish the episode to the RSS feed.",
    badgeStyle: "background-color: #1e3a8a; color: #93c5fd; border: 1px solid #1e40af;",
  },
  published: {
    label: "Published",
    description: "Episode is active and listed in the public RSS feed.",
    severity: "success",
    nextAction: "Episode is live.",
    badgeStyle: "background-color: #047857; color: #34d399; border: 1px solid #059669;",
  },
};

export function getStatusDisplay(status: string): StatusUI {
  const normalized = status.toLowerCase().trim();
  if (statusMap[normalized]) {
    return statusMap[normalized];
  }
  return {
    label: status,
    description: `Status: ${status}`,
    severity: "info",
    nextAction: "Monitor pipeline status.",
    badgeStyle: "background-color: #1e293b; color: #94a3b8; border: 1px solid #334155;",
  };
}
