"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createPodcast, updatePodcast } from "@/app/app/podcasts/actions";
import { WEEKDAYS, WEEKDAY_LABELS, SEGMENT_MIN, SEGMENT_MAX, SEGMENT_DEFAULT, type PodcastInput } from "@/app/app/podcasts/config";
import { VERTICALS, teamLeagueIdsForVerticals } from "@/lib/verticals";
import { defaultShowForgeState, templateBible, type ShowBible, type ShowForgeState, type ShowStoryline } from "@/lib/shows/showForge";
import { Button, ButtonLink, Field, Input, Textarea, Select, StatusBadge, Card, Checkbox } from "@/components/studio";

export interface WizardHost { id: string; name: string; role: string }
export interface WizardTeam { id: string; leagueId: string; name: string }
export interface WizardInitial { name?: string; cadence?: "one_time" | "recurring"; scheduleDays?: string[]; verticals?: string[]; teams?: string[]; segmentCount?: number; hostIds?: string[]; showForge?: ShowForgeState }

const STEPS = ["Spark", "Promise", "World", "Cast", "Episode DNA", "Storylines", "Schedule", "Launch"];
const TEMPLATES: Array<{ id: ShowBible["templateId"]; title: string; description: string }> = [
  { id: "rivalry_room", title: "The Rivalry Room", description: "Two believers with different standards and no fake neutrality." },
  { id: "insider_room", title: "Inside the Building", description: "Decisions, incentives, and the people who pay for them." },
  { id: "fan_court", title: "Fan Court", description: "Put the decision on trial from the fan’s seat." },
  { id: "season_story", title: "The Season Story", description: "Complete episodes that also advance a larger chapter." },
  { id: "custom", title: "Build your own", description: "Start with a clean creative room." },
];
const TONES: Array<{ value: ShowBible["tone"]; label: string }> = [
  { value: "combustible", label: "Combustible" }, { value: "smart_funny", label: "Smart and funny" }, { value: "intimate", label: "Intimate" }, { value: "cinematic", label: "Cinematic" }, { value: "fast_loose", label: "Fast and loose" },
];

function id(prefix: string) { return `${prefix}-${typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID().slice(0, 8) : Math.random().toString(36).slice(2, 10)}`; }
function starterStoryline(hostIds: string[]): ShowStoryline { return { id: id("arc"), title: "The argument that changes them", premise: "A recurring disagreement exposes a deeper difference in how the hosts judge loyalty, power, or accountability.", status: "active", priority: 3, featuredHostIds: hostIds, beats: [{ title: "Plant the fault line", direction: "Let the hosts discover the deeper disagreement naturally without announcing an arc." }, { title: "Make it cost", direction: "Force one host to defend the earlier standard while the other names its human cost." }, { title: "Earn movement", direction: "Let one host sharpen or change a position in a way that costs them something." }] }; }

export default function ShowForgeWizard({ hosts, teams, initial = {}, podcastId, prefillTopicTitle }: { hosts: WizardHost[]; teams: WizardTeam[]; initial?: WizardInitial; podcastId?: string; prefillTopicTitle?: string }) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [furthest, setFurthest] = useState(0);
  const [name, setName] = useState(initial.name || "");
  const [cadence, setCadence] = useState<"one_time" | "recurring">(initial.cadence || "recurring");
  const [scheduleDays, setScheduleDays] = useState(initial.scheduleDays || ["mon"]);
  const [verticals, setVerticals] = useState(initial.verticals || []);
  const [teamIds, setTeamIds] = useState(initial.teams || []);
  const [segmentCount, setSegmentCount] = useState(initial.segmentCount || SEGMENT_DEFAULT);
  const [hostIds, setHostIds] = useState(initial.hostIds || []);
  const [forge, setForge] = useState<ShowForgeState>(initial.showForge || defaultShowForgeState());
  const [error, setError] = useState<string | null>(null);
  const [successId, setSuccessId] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const bible = forge.bible;
  const selectedHosts = hosts.filter(host => hostIds.includes(host.id));
  const availableTeams = useMemo(() => { const leagues = new Set(teamLeagueIdsForVerticals(verticals)); return teams.filter(team => leagues.has(team.leagueId)); }, [teams, verticals]);
  const setBible = <K extends keyof ShowBible>(key: K, value: ShowBible[K]) => setForge(current => ({ ...current, bible: { ...current.bible, [key]: value } }));
  const toggle = (value: string, values: string[], max?: number) => values.includes(value) ? values.filter(item => item !== value) : max && values.length >= max ? values : [...values, value];
  const updateStory = (index: number, patch: Partial<ShowStoryline>) => setForge(current => ({ ...current, storylines: current.storylines.map((story, i) => i === index ? { ...story, ...patch } : story) }));

  const validation = () => {
    if (step === 0 && !name.trim()) return "Give the show a name.";
    if (step === 1 && (bible.premise.trim().length < 8 || bible.audiencePromise.trim().length < 8 || bible.pointOfView.trim().length < 4)) return "Complete the premise, listener promise, and point of view.";
    if (step === 2 && verticals.length === 0) return "Choose at least one sports world.";
    if (step === 3 && hostIds.length === 0) return "Choose at least one host.";
    if (step === 4 && bible.recurringSegments.length === 0) return "Add at least one recurring segment.";
    if (step === 5) for (const story of forge.storylines) { if (!story.title.trim() || !story.premise.trim()) return "Every storyline needs a title and premise."; if (story.beats.length < 2 || story.beats.some(beat => !beat.title.trim() || !beat.direction.trim())) return `Finish at least two beats in ${story.title || "the storyline"}.`; }
    if (step === 6 && cadence === "recurring" && scheduleDays.length === 0) return "Choose at least one release day.";
    return null;
  };
  const next = () => { const message = validation(); if (message) { setError(message); return; } setError(null); const nextStep = Math.min(STEPS.length - 1, step + 1); setStep(nextStep); setFurthest(current => Math.max(current, nextStep)); };
  const submit = () => {
    const message = validation(); if (message) { setError(message); return; }
    const input: PodcastInput = { name: name.trim(), cadence, scheduleDays, verticals, teams: teamIds, segmentCount, hostIds, showForge: forge };
    startTransition(async () => { const result = podcastId ? await updatePodcast(podcastId, input) : await createPodcast(input); if (!result.success) { setError(result.error); return; } setSuccessId(result.podcastId); router.refresh(); });
  };

  if (successId) return <Card className="forgeSuccess"><StatusBadge tone="success">Saved</StatusBadge><h2>{podcastId ? "Show bible updated" : "Your show is ready"}</h2><p><strong>{name}</strong> now has a premise, listener promise, cast, episode DNA, schedule, and {forge.storylines.length} storyline{forge.storylines.length === 1 ? "" : "s"}.</p><div><ButtonLink href={`/studio/shows/${successId}`} variant="primary">Open show headquarters</ButtonLink><ButtonLink href="/studio/shows" variant="secondary">All shows</ButtonLink></div></Card>;

  const required = [name.trim(), bible.premise.trim(), verticals.length, hostIds.length, bible.recurringSegments.length, cadence === "one_time" || scheduleDays.length];
  return <div className="forgeWorkspace">
    <nav className="forgeSteps" aria-label="Show Forge steps">{STEPS.map((label, index) => <button key={label} type="button" className={index === step ? "isCurrent" : index < step || index <= furthest ? "isComplete" : ""} disabled={index > furthest} onClick={() => setStep(index)}><span>{index < step ? "✓" : index + 1}</span><strong>{label}</strong></button>)}</nav>
    <section className="forgeMain" aria-labelledby="forge-step-title"><header><span>Step {step + 1} of {STEPS.length}</span><h2 id="forge-step-title">{STEPS[step]}</h2></header>
      {step === 0 && <div className="forgeFields"><Field label="Show name" help="The title listeners will see."><Input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="The Fourth Quarter" /></Field><div><h3>Choose a starting world</h3><div className="forgeChoiceGrid">{TEMPLATES.map(template => <button key={template.id} type="button" className={bible.templateId === template.id ? "isSelected" : ""} onClick={() => setForge(current => ({ ...current, bible: templateBible(template.id) }))}><strong>{template.title}</strong><span>{template.description}</span></button>)}</div></div>{prefillTopicTitle && <p className="forgeNote">The premiere can begin with <strong>{prefillTopicTitle}</strong>.</p>}</div>}
      {step === 1 && <div className="forgeFields"><Field label="What is the show really about?" help="The human question, not simply the sport."><Textarea value={bible.premise} onChange={event => setBible("premise", event.target.value)} /></Field><Field label="What does the listener consistently get?"><Textarea value={bible.audiencePromise} onChange={event => setBible("audiencePromise", event.target.value)} /></Field><Field label="How does the show judge a story?"><Textarea value={bible.pointOfView} onChange={event => setBible("pointOfView", event.target.value)} /></Field><Field label="Tone"><Select value={bible.tone} onChange={event => setBible("tone", event.target.value as ShowBible["tone"])}>{TONES.map(tone => <option key={tone.value} value={tone.value}>{tone.label}</option>)}</Select></Field></div>}
      {step === 2 && <div className="forgeFields"><div><h3>Sports worlds</h3><div className="forgePills">{VERTICALS.map(vertical => <button key={vertical} type="button" className={verticals.includes(vertical) ? "isSelected" : ""} onClick={() => { const next = toggle(vertical, verticals); setVerticals(next); const legal = new Set(teamLeagueIdsForVerticals(next)); setTeamIds(current => current.filter(teamId => teams.some(team => team.id === teamId && legal.has(team.leagueId)))); }}>{vertical}</button>)}</div></div>{availableTeams.length > 0 && <div><h3>Specific teams <small>optional</small></h3><div className="forgeTeamGrid">{availableTeams.map(team => <Checkbox key={team.id} label={team.name} checked={teamIds.includes(team.id)} onChange={() => setTeamIds(toggle(team.id, teamIds))} />)}</div></div>}</div>}
      {step === 3 && <div className="forgeFields"><div><h3>Cast up to two hosts</h3><div className="forgeChoiceGrid">{hosts.map(host => <button key={host.id} type="button" className={hostIds.includes(host.id) ? "isSelected" : ""} onClick={() => setHostIds(toggle(host.id, hostIds, 2))}><strong>{host.name}</strong><span>{host.role}</span></button>)}</div></div><Field label="Host chemistry" help="What do they admire, resent, misunderstand, or need from each other?"><Textarea value={bible.hostChemistry} onChange={event => setBible("hostChemistry", event.target.value)} /></Field></div>}
      {step === 4 && <div className="forgeFields"><Field label={`Researched stories per episode: ${segmentCount}`}><input type="range" min={SEGMENT_MIN} max={SEGMENT_MAX} value={segmentCount} onChange={event => setSegmentCount(Number(event.target.value))} /></Field><div className="forgeTwoColumns"><Field label="Opening ritual"><Textarea value={bible.openingRitual} onChange={event => setBible("openingRitual", event.target.value)} /></Field><Field label="Closing ritual"><Textarea value={bible.closingRitual} onChange={event => setBible("closingRitual", event.target.value)} /></Field></div><div><div className="forgeInlineHead"><h3>Recurring segment library</h3><Button type="button" size="compact" onClick={() => setBible("recurringSegments", [...bible.recurringSegments, { id: id("segment"), name: "New segment", purpose: "What this segment adds to the episode.", frequency: "often" }])}>Add segment</Button></div><div className="forgeStack">{bible.recurringSegments.map((segment, index) => <Card key={segment.id} className="forgeSubcard"><Input value={segment.name} aria-label="Segment name" onChange={event => setBible("recurringSegments", bible.recurringSegments.map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /><Textarea value={segment.purpose} aria-label="Segment purpose" onChange={event => setBible("recurringSegments", bible.recurringSegments.map((item, i) => i === index ? { ...item, purpose: event.target.value } : item))} /><div className="forgeInlineHead"><Select value={segment.frequency} aria-label="Segment frequency" onChange={event => setBible("recurringSegments", bible.recurringSegments.map((item, i) => i === index ? { ...item, frequency: event.target.value as typeof item.frequency } : item))}><option value="every_episode">Every episode</option><option value="often">Often</option><option value="occasionally">Occasionally</option></Select>{bible.recurringSegments.length > 1 && <Button variant="destructive" size="compact" onClick={() => setBible("recurringSegments", bible.recurringSegments.filter((_, i) => i !== index))}>Remove</Button>}</div></Card>)}</div></div></div>}
      {step === 5 && <div className="forgeFields"><div className="forgeInlineHead"><div><h3>Season storylines</h3><p>Each beat changes framing or relationships without inventing facts.</p></div><Button type="button" onClick={() => setForge(current => ({ ...current, storylines: [...current.storylines, starterStoryline(hostIds)] }))}>Add storyline</Button></div>{forge.storylines.length === 0 ? <p className="forgeNote">Storylines are optional. Standalone episodes still follow the show bible.</p> : <div className="forgeStack">{forge.storylines.map((story, storyIndex) => <Card key={story.id} className="forgeSubcard"><div className="forgeInlineHead"><Input value={story.title} aria-label="Storyline title" onChange={event => updateStory(storyIndex, { title: event.target.value })} /><Button variant="destructive" size="compact" onClick={() => setForge(current => ({ ...current, storylines: current.storylines.filter((_, i) => i !== storyIndex) }))}>Remove</Button></div><Textarea value={story.premise} aria-label="Storyline premise" onChange={event => updateStory(storyIndex, { premise: event.target.value })} /><div className="forgeTwoColumns"><Field label="Status"><Select value={story.status} onChange={event => updateStory(storyIndex, { status: event.target.value as ShowStoryline["status"] })}><option value="active">Active</option><option value="paused">Paused</option><option value="resolved">Resolved</option></Select></Field><Field label="Priority"><Select value={story.priority} onChange={event => updateStory(storyIndex, { priority: Number(event.target.value) })}>{[1,2,3,4,5].map(value => <option key={value} value={value}>{value}</option>)}</Select></Field></div><div className="forgeStack">{story.beats.map((beat, beatIndex) => <div key={`${story.id}-${beatIndex}`} className="forgeBeat"><Input value={beat.title} aria-label={`Beat ${beatIndex + 1} title`} onChange={event => updateStory(storyIndex, { beats: story.beats.map((item, i) => i === beatIndex ? { ...item, title: event.target.value } : item) })} /><Textarea value={beat.direction} aria-label={`Beat ${beatIndex + 1} direction`} onChange={event => updateStory(storyIndex, { beats: story.beats.map((item, i) => i === beatIndex ? { ...item, direction: event.target.value } : item) })} />{story.beats.length > 2 && <Button variant="ghost" size="compact" onClick={() => updateStory(storyIndex, { beats: story.beats.filter((_, i) => i !== beatIndex) })}>Remove beat</Button>}</div>)}<Button size="compact" onClick={() => updateStory(storyIndex, { beats: [...story.beats, { title: `Beat ${story.beats.length + 1}`, direction: "Describe the creative movement without inventing facts." }] })}>Add beat</Button></div></Card>)}</div>}</div>}
      {step === 6 && <div className="forgeFields"><Field label="Release mode"><Select value={cadence} onChange={event => setCadence(event.target.value as typeof cadence)}><option value="recurring">Recurring show</option><option value="one_time">Manual releases</option></Select></Field>{cadence === "recurring" && <div><h3>Release days</h3><div className="forgePills">{WEEKDAYS.map(day => <button key={day} type="button" className={scheduleDays.includes(day) ? "isSelected" : ""} onClick={() => setScheduleDays(toggle(day, scheduleDays))}>{WEEKDAY_LABELS[day]}</button>)}</div></div>}</div>}
      {step === 7 && <div className="forgeReview"><StatusBadge tone={required.every(Boolean) ? "success" : "warning"}>{required.every(Boolean) ? "Ready to launch" : "Needs attention"}</StatusBadge><h3>{name || "Untitled show"}</h3><dl><div><dt>Premise</dt><dd>{bible.premise}</dd></div><div><dt>Cast</dt><dd>{selectedHosts.map(host => host.name).join(" + ") || "Not assigned"}</dd></div><div><dt>World</dt><dd>{verticals.join(", ") || "Not selected"}</dd></div><div><dt>Cadence</dt><dd>{cadence === "recurring" ? scheduleDays.map(day => WEEKDAY_LABELS[day]).join(", ") : "Manual"}</dd></div><div><dt>Storylines</dt><dd>{forge.storylines.length}</dd></div></dl></div>}
      {error && <p className="forgeError" role="alert">{error}</p>}
      <footer className="forgeActions"><Button variant="ghost" disabled={step === 0 || pending} onClick={() => setStep(current => Math.max(0, current - 1))}>Back</Button>{step < STEPS.length - 1 ? <Button variant="primary" onClick={next}>Continue</Button> : <Button variant="primary" disabled={pending} onClick={submit}>{pending ? "Saving…" : podcastId ? "Save show bible" : "Create show"}</Button>}</footer>
    </section>
    <aside className="forgeSummary"><span>Live summary</span><h3>{name || "Untitled show"}</h3><dl><div><dt>Format</dt><dd>{TEMPLATES.find(template => template.id === bible.templateId)?.title}</dd></div><div><dt>Hosts</dt><dd>{selectedHosts.map(host => host.name).join(" + ") || "Not selected"}</dd></div><div><dt>Sports</dt><dd>{verticals.join(", ") || "Not selected"}</dd></div><div><dt>Cadence</dt><dd>{cadence === "recurring" ? scheduleDays.map(day => WEEKDAY_LABELS[day]).join(", ") : "Manual"}</dd></div><div><dt>Story arcs</dt><dd>{forge.storylines.length}</dd></div></dl><div className="forgeRequirements"><strong>Requirements</strong>{required.map((complete, index) => <span key={index} className={complete ? "isComplete" : ""}>{complete ? "✓" : "○"} {['Name','Promise','Sports world','Cast','Episode DNA','Schedule'][index]}</span>)}</div></aside>
  </div>;
}
